import { randomUUID } from "node:crypto";
import type { Pool,PoolClient } from "pg";
import { nextOccurrences,misfireOutcome,type ScheduleDefinition,type ScheduleSpec } from "./schedule.js";

interface ScheduleRow {id:string;workspace_id:string;environment_id:string;deployment_id:string;workflow_revision_id:string;schedule_type:ScheduleSpec["type"];schedule_spec:ScheduleSpec["spec"];time_zone:string;dst_policy:ScheduleDefinition["dstPolicy"];start_at:Date|null;end_at:Date|null;misfire_policy:"queue"|"skip"|"expire"|"fallback_pool";misfire_grace_seconds:number;jitter_seconds:number;no_runner_policy:Record<string,unknown>;routing_requirements:Record<string,unknown>;encrypted_payload_reference:string;next_run_at:Date;}
export interface TickResult {leader:boolean;examined:number;queued:number;skipped:number;expired:number}

export class PostgresScheduler {
  constructor(private readonly pool:Pool){}
  async tick(now:Date,limit=100):Promise<TickResult>{const client=await this.pool.connect();try{await client.query("BEGIN");const leader=await client.query<{leader:boolean}>(`SELECT pg_try_advisory_xact_lock(hashtext('sandbox-durable-scheduler')) leader`);if(!leader.rows[0].leader){await client.query("COMMIT");return{leader:false,examined:0,queued:0,skipped:0,expired:0};}const due=await client.query<ScheduleRow>(`SELECT id,workspace_id,environment_id,deployment_id,workflow_revision_id,schedule_type,schedule_spec,time_zone,dst_policy,start_at,end_at,misfire_policy,misfire_grace_seconds,jitter_seconds,no_runner_policy,routing_requirements,encrypted_payload_reference,next_run_at FROM workflow_schedules WHERE paused_at IS NULL AND next_run_at<=$1 AND (end_at IS NULL OR next_run_at<=end_at) ORDER BY next_run_at FOR UPDATE SKIP LOCKED LIMIT $2`,[now,Math.min(Math.max(limit,1),1000)]);const result:TickResult={leader:true,examined:due.rowCount??0,queued:0,skipped:0,expired:0};for(const schedule of due.rows){const outcome=misfireOutcome(schedule.next_run_at,now,schedule.misfire_grace_seconds,schedule.misfire_policy);const eventId=randomUUID(),queueId=eventId,emissionId=randomUUID();if(outcome==="skip"){await this.emission(client,schedule,emissionId,schedule.next_run_at,null,"skipped","Schedule misfire policy skipped this occurrence.",now);result.skipped++;}else if(outcome==="expire"){await this.insertEvent(client,schedule,queueId,eventId,schedule.next_run_at,schedule.next_run_at,"expired",now);await this.emission(client,schedule,emissionId,schedule.next_run_at,queueId,"expired","Schedule occurrence expired under its misfire policy.",now);result.expired++;}else{const routing=outcome==="fallback_pool"?{...schedule.routing_requirements,fallback:schedule.no_runner_policy}:schedule.routing_requirements;await this.insertEvent(client,{...schedule,routing_requirements:routing},queueId,eventId,schedule.next_run_at,null,"queued",now);await this.emission(client,schedule,emissionId,schedule.next_run_at,queueId,"queued",outcome==="fallback_pool"?"Approved fallback routing attached.":null,now);result.queued++;}const [next]=nextOccurrences(definition(schedule),schedule.next_run_at,1);await client.query(`UPDATE workflow_schedules SET last_scheduled_at=$2,next_run_at=$3,updated_at=$4 WHERE id=$1`,[schedule.id,schedule.next_run_at,next??null,now]);}await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
  async backfill(scheduleId:string,from:Date,to:Date,requestedAt:Date,maximum=1000):Promise<number>{if(to<=from)throw new Error("Backfill end must be after start.");const client=await this.pool.connect();try{await client.query("BEGIN");const result=await client.query<ScheduleRow>(`SELECT id,workspace_id,environment_id,deployment_id,workflow_revision_id,schedule_type,schedule_spec,time_zone,dst_policy,start_at,end_at,misfire_policy,misfire_grace_seconds,jitter_seconds,no_runner_policy,routing_requirements,encrypted_payload_reference,next_run_at FROM workflow_schedules WHERE id=$1 FOR UPDATE`,[scheduleId]);if(!result.rowCount)throw new Error("Schedule not found.");const schedule=result.rows[0];const dates=nextOccurrences(definition(schedule),new Date(from.getTime()-1),Math.min(Math.max(maximum,1),1000)).filter(date=>date<=to);let created=0;for(const scheduledFor of dates){const eventId=randomUUID();const inserted=await this.insertEvent(client,schedule,eventId,eventId,scheduledFor,null,"queued",requestedAt);if(inserted)created++;await this.emission(client,schedule,randomUUID(),scheduledFor,inserted?eventId:null,inserted?"queued":"skipped",inserted?"Manual backfill.":"Occurrence was already emitted.",requestedAt);}await client.query("COMMIT");return created;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
  private async insertEvent(client:PoolClient,schedule:ScheduleRow,id:string,eventId:string,scheduledFor:Date,expiresAt:Date|null,status:"queued"|"expired",now:Date):Promise<boolean>{const result=await client.query(`INSERT INTO queued_events(id,event_id,original_event_id,workspace_id,workflow_revision_id,deployment_id,trigger_type,trigger_reference,created_at,available_at,expires_at,maximum_attempts,idempotency_key,routing_requirements,encrypted_payload_reference,status,correlation_id) VALUES($1,$2,$2,$3,$4,$5,'schedule',$6,$7,$8,$9,5,$10,$11,$12,$13,$14) ON CONFLICT DO NOTHING`,[id,eventId,schedule.workspace_id,schedule.workflow_revision_id,schedule.deployment_id,schedule.id,now,scheduledFor,expiresAt,`schedule:${schedule.id}:${scheduledFor.toISOString()}`,JSON.stringify(schedule.routing_requirements),schedule.encrypted_payload_reference,status,randomUUID()]);return Boolean(result.rowCount);}
  private async emission(client:PoolClient,schedule:ScheduleRow,id:string,scheduledFor:Date,queueId:string|null,outcome:"queued"|"skipped"|"expired",reason:string|null,now:Date):Promise<void>{await client.query(`INSERT INTO schedule_emissions(id,schedule_id,scheduled_for,queued_event_id,outcome,reason,emitted_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(schedule_id,scheduled_for) DO NOTHING`,[id,schedule.id,scheduledFor,queueId,outcome,reason,now]);}
}
function definition(row:ScheduleRow):ScheduleDefinition{return{scheduleId:row.id,timeZone:row.time_zone,dstPolicy:row.dst_policy,startAt:row.start_at,endAt:row.end_at,jitterSeconds:row.jitter_seconds,schedule:{type:row.schedule_type,spec:row.schedule_spec} as ScheduleSpec};}

