import { describe,expect,it } from "vitest";
import { RUNNER_PROTOCOL_VERSION,type RunnerIdentity,type RunnerRequirements } from "@sandbox/contracts";
import { estimateHostedUsage,requireDeploymentTransition,validateDeployment,type DeploymentValidationInput } from "./deployment.js";

const workspaceId="10000000-0000-4000-8000-000000000001",environmentId="20000000-0000-4000-8000-000000000002",connectionId="30000000-0000-4000-8000-000000000003";
const requirements:RunnerRequirements={protocolVersion:RUNNER_PROTOCOL_VERSION,engineVersion:"0.4.0",pluginRuntimeVersion:"0.4.0",runnerTypes:["hosted"],architectures:["x86_64"],workspaceId,environmentId,region:"eu-west-2",requiredTags:[],capabilities:[{nodeType:"http_request",nodeVersions:[1],constraints:{}}],plugins:[],connectionIds:[connectionId],minimumAvailableConcurrency:1};
const runner:RunnerIdentity={runnerId:"40000000-0000-4000-8000-000000000004",keyId:"key",runnerType:"hosted",protocolVersion:RUNNER_PROTOCOL_VERSION,engineVersion:"0.4.0",pluginRuntimeVersion:"0.4.0",architecture:"x86_64",operatingSystem:"linux",workspaceId,environmentId,region:"eu-west-2",tags:[],concurrencyLimit:4,maintenanceState:"active",nodeCapabilities:requirements.capabilities,plugins:[],connections:[{connectionId,environmentId,operations:["send"],status:"available"}]};
const estimate=estimateHostedUsage({periodDays:30,scheduleExecutions:30,historicLocalDurationSeconds:2,configuredTimeoutSeconds:30,browserRequired:false,maximumAttempts:2,expectedConcurrency:1});
const input:DeploymentValidationInput={target:"managed_cloud_runner",region:"eu-west-2",requirements,nodes:[{nodeId:"http",nodeType:"http_request",nodeVersion:1,plugin:null,requiresBrowser:false,requiresLocalFile:false,localFileLabel:null,requiredConnectionIds:[connectionId],requiredEnvironmentVariables:["API_HOST"],networkTargets:["https://api.example.com"],approvalRequired:false}],graphIssues:[],availableRunners:[runner],availableConnectionIds:[connectionId],availableEnvironmentVariables:["API_HOST"],approvedNetworkTargets:["https://api.example.com"],approvedPluginPackages:[],approvalSnapshotPresent:true,concurrencyLimit:1,retentionDays:30,estimatedUsage:estimate};

describe("deployment validation",()=>{
  it("validates every predictable dependency before deployment",()=>{expect(validateDeployment(input)).toMatchObject({valid:true,compatibleRunnerIds:[runner.runnerId],unavailableLocalFiles:[]});});
  it("blocks unresolved connections, local files and capability mismatch",()=>{const result=validateDeployment({...input,availableConnectionIds:[],availableRunners:[],nodes:[{...input.nodes[0],requiresLocalFile:true,localFileLabel:"Quarterly report.xlsx"}]});expect(result.valid).toBe(false);expect(result.issues.map(issue=>issue.code)).toEqual(expect.arrayContaining(["connection_unresolved","local_file_unavailable","runner_incompatible"]));});
  it("keeps estimates explicitly non-guaranteed and separates browser duration",()=>{const browser=estimateHostedUsage({periodDays:7,scheduleExecutions:10,historicLocalDurationSeconds:null,configuredTimeoutSeconds:60,browserRequired:true,maximumAttempts:1,expectedConcurrency:2});expect(browser).toMatchObject({hostedExecutionSeconds:0,browserWorkerSeconds:600,confidence:"low",disclaimer:"Estimate only; actual usage and cost may differ."});});
  it("rejects invalid deployment state rewrites",()=>{expect(()=>requireDeploymentTransition("active","deploying")).toThrow(/not allowed/i);expect(()=>requireDeploymentTransition("active","rolled_back")).not.toThrow();});
});
