import {randomUUID} from "node:crypto";
import {Pool} from "pg";
import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {PostgresPrivacyService} from "./privacy.js";
import type {AuthenticatedSession} from "./types.js";

const connectionString=process.env.TEST_DATABASE_URL,integration=connectionString?describe:describe.skip;
integration("enforceable privacy lifecycle",()=>{
  const pool=new Pool({connectionString,max:4}),privacy=new PostgresPrivacyService(pool),accountId=randomUUID(),organisationId=randomUUID(),workspaceId=randomUUID(),roleId=randomUUID(),auditId=randomUUID();
  const actor:AuthenticatedSession={accountId,sessionId:randomUUID(),subject:`privacy:${accountId}`,email:`${accountId}@example.invalid`,issuedAt:new Date(),expiresAt:new Date(Date.now()+3_600_000),authenticationMethods:["passkey"],platformPermissions:[]};
  beforeAll(async()=>{await pool.query(`INSERT INTO accounts(id,identity_subject,primary_email,email_verified,display_name) VALUES($1,$2,$3,true,'Privacy customer')`,[accountId,actor.subject,actor.email]);await pool.query(`INSERT INTO organisations(id,name,slug,created_by) VALUES($1,'Privacy test',$2,$3)`,[organisationId,`privacy-${organisationId}`,accountId]);await pool.query(`INSERT INTO roles(id,organisation_id,role_key,display_name,built_in) VALUES($1,$2,'administrator','Administrator',true)`,[roleId,organisationId]);await pool.query(`INSERT INTO memberships(organisation_id,account_id,role_id) VALUES($1,$2,$3)`,[organisationId,accountId,roleId]);await pool.query(`INSERT INTO workspaces(id,organisation_id,name,slug,created_by) VALUES($1,$2,'Privacy workspace','privacy',$3)`,[workspaceId,organisationId,accountId]);await pool.query(`INSERT INTO workspace_memberships(workspace_id,account_id,role_id) VALUES($1,$2,$3)`,[workspaceId,accountId,roleId]);await pool.query(`INSERT INTO audit_events(id,occurred_at,actor_account_id,workspace_id,action,resource_type,resource_id,correlation_id) VALUES($1,$2,$3,$4,'privacy.test','workspace',$6,$5)`,[auditId,new Date(Date.now()-400*86_400_000),accountId,workspaceId,randomUUID(),workspaceId]);});
  afterAll(async()=>{await pool.end();});
  it("exports account data, enforces retention, and completes irreversible pseudonymization",async()=>{const policy=await privacy.setRetention(actor,workspaceId,{executionDetailDays:90,queueEventDays:30,webhookDeliveryDays:7,runnerCommandDays:30,auditEventDays:365});expect(policy.auditEventDays).toBe(365);const exported=await privacy.exportAccount(actor);expect(exported).toMatchObject({exportVersion:1,account:{id:accountId},workspaceMemberships:[{workspace_id:workspaceId}]});const sweep=await privacy.runRetentionSweep(new Date(),1000,workspaceId);expect(sweep.auditEvents).toBe(1);expect((await pool.query(`SELECT 1 FROM audit_events WHERE id=$1`,[auditId])).rowCount).toBe(0);const deleted=await privacy.deleteAccount(actor,"privacy-correlation-0001");expect(deleted.summary).toMatchObject({workspaceMemberships:1,organisationMemberships:1});const account=(await pool.query<{identity_subject:string;primary_email:string;display_name:string;deleted_at:Date}>(`SELECT identity_subject,primary_email,display_name,deleted_at FROM accounts WHERE id=$1`,[accountId])).rows[0];expect(account).toMatchObject({identity_subject:`deleted:${accountId}`,primary_email:`deleted+${accountId}@invalid.local`,display_name:"Deleted account",deleted_at:expect.any(Date)});expect((await pool.query(`SELECT status FROM privacy_deletion_requests WHERE id=$1`,[deleted.requestId])).rows[0].status).toBe("completed");});
});
