import { randomUUID } from "node:crypto";
import type { Pool,PoolClient } from "pg";
import type { AuthenticatedSession } from "./types.js";
import { DomainError } from "./types.js";

export interface WorkspaceRetentionPolicy {executionDetailDays:number;queueEventDays:number;webhookDeliveryDays:number;runnerCommandDays:number;auditEventDays:number;changedBy:string|null;changedAt:string|null}
export interface RetentionSweepResult {workspaces:number;executionDetails:number;queueEvents:number;webhookDeliveries:number;runnerCommands:number;auditEvents:number;operationalEvidence:number}
export interface PrivacyAdministration {
  getRetention(workspaceId:string):Promise<WorkspaceRetentionPolicy>;
  setRetention(actor:AuthenticatedSession,workspaceId:string,policy:Omit<WorkspaceRetentionPolicy,"changedBy"|"changedAt">):Promise<WorkspaceRetentionPolicy>;
  exportAccount(actor:AuthenticatedSession):Promise<Record<string,unknown>>;
  deleteAccount(actor:AuthenticatedSession,correlationId:string):Promise<{requestId:string;completedAt:string;summary:Record<string,number>}>;
}

export const DATA_CLASSIFICATION={
  account_identity:{classification:"personal",examples:["email","display name","identity subject"],retention:"Until account deletion; then irreversible pseudonymization."},
  authentication:{classification:"secret",examples:["session identifiers","token hashes","device public keys"],retention:"Expiry/revocation or immediate account deletion."},
  workflow_content:{classification:"customer_content",examples:["encrypted revisions","protected variables"],retention:"Owner/workspace lifecycle; personal workflows deleted with the account."},
  execution_detail:{classification:"customer_content",examples:["event metadata","checkpoints","payload references"],retention:"Workspace executionDetailDays; summary row retained without detail."},
  webhook_payload:{classification:"customer_content",examples:["encrypted webhook delivery body"],retention:"Earlier of endpoint expiry and workspace webhookDeliveryDays."},
  operational_evidence:{classification:"security_record",examples:["audit events","incident and support timelines"],retention:"Workspace auditEventDays or documented platform schedule."},
  billing_record:{classification:"financial_record",examples:["usage ledger","invoice reconciliation","referral rewards"],retention:"Statutory/contractual schedule; excluded from customer-configurable purge."}
} as const;

interface PolicyRow {execution_detail_days:number;queue_event_days:number;webhook_delivery_days:number;runner_command_days:number;audit_event_days:number;changed_by:string|null;changed_at:Date|null}

export class PostgresPrivacyService implements PrivacyAdministration {
  constructor(private readonly pool:Pool){}

  async getRetention(workspaceId:string):Promise<WorkspaceRetentionPolicy>{return this.transaction("privacy_service",async client=>policyFromRow((await client.query<PolicyRow>(`SELECT COALESCE(policy.execution_detail_days,90) execution_detail_days,COALESCE(policy.queue_event_days,30) queue_event_days,COALESCE(policy.webhook_delivery_days,7) webhook_delivery_days,COALESCE(policy.runner_command_days,30) runner_command_days,COALESCE(policy.audit_event_days,2555) audit_event_days,policy.changed_by,policy.changed_at FROM workspaces workspace LEFT JOIN workspace_data_retention policy ON policy.workspace_id=workspace.id WHERE workspace.id=$1`,[workspaceId])).rows[0]??notFound()));}

  async setRetention(actor:AuthenticatedSession,workspaceId:string,policy:Omit<WorkspaceRetentionPolicy,"changedBy"|"changedAt">):Promise<WorkspaceRetentionPolicy>{validateRetentionPolicy(policy);return this.transaction("privacy_service",async client=>policyFromRow((await client.query<PolicyRow>(`INSERT INTO workspace_data_retention(workspace_id,execution_detail_days,queue_event_days,webhook_delivery_days,runner_command_days,audit_event_days,changed_by,changed_at) VALUES($1,$2,$3,$4,$5,$6,$7,now()) ON CONFLICT(workspace_id) DO UPDATE SET execution_detail_days=excluded.execution_detail_days,queue_event_days=excluded.queue_event_days,webhook_delivery_days=excluded.webhook_delivery_days,runner_command_days=excluded.runner_command_days,audit_event_days=excluded.audit_event_days,changed_by=excluded.changed_by,changed_at=excluded.changed_at RETURNING *`,[workspaceId,policy.executionDetailDays,policy.queueEventDays,policy.webhookDeliveryDays,policy.runnerCommandDays,policy.auditEventDays,actor.accountId])).rows[0]));}

  async exportAccount(actor:AuthenticatedSession):Promise<Record<string,unknown>>{return this.transaction("privacy_service",async client=>{
    const account=await client.query(`SELECT id,primary_email,email_verified,display_name,created_at,deleted_at FROM accounts WHERE id=$1`,[actor.accountId]);
    if(!account.rowCount)throw new DomainError("account_not_found","Account was not found.",404);
    const [memberships,workspaceMemberships,sessions,invitations,tokens,workflows,audit,referrals]=await Promise.all([
      client.query(`SELECT organisation_id,role_id,status,joined_at,removed_at FROM memberships WHERE account_id=$1 ORDER BY joined_at`,[actor.accountId]),
      client.query(`SELECT workspace_id,role_id,created_at FROM workspace_memberships WHERE account_id=$1 ORDER BY created_at`,[actor.accountId]),
      client.query(`SELECT id,device_name,created_at,last_seen_at,expires_at,revoked_at FROM account_sessions WHERE account_id=$1 ORDER BY created_at`,[actor.accountId]),
      client.query(`SELECT id,organisation_id,email,status,expires_at,accepted_at,revoked_at,created_at FROM invitations WHERE invited_by=$1 OR accepted_by=$1 ORDER BY created_at`,[actor.accountId]),
      client.query(`SELECT id,token_kind,token_prefix,name,organisation_id,scopes,workspace_restrictions,environment_restrictions,created_at,expires_at,last_used_at,revoked_at FROM access_tokens WHERE owner_account_id=$1 ORDER BY created_at`,[actor.accountId]),
      client.query(`SELECT id,name,created_at,deleted_at,current_published_revision_id,current_draft_revision_id FROM synced_workflows WHERE owner_type='personal' AND owner_id=$1 ORDER BY created_at`,[actor.accountId]),
      client.query(`SELECT id,occurred_at,workspace_id,action,resource_type,resource_id,before_summary,after_summary,correlation_id FROM audit_events WHERE actor_account_id=$1 ORDER BY occurred_at,id`,[actor.accountId]),
      client.query(`SELECT referral.id,CASE WHEN referral.referrer_account_id=$1 THEN 'referrer' ELSE 'referred' END relationship,referral.status,referral.claimed_at,referral.qualified_at,referral.rewarded_at,referral.reversed_at,reward.amount_microusd,reward.created_at reward_created_at,reward.reversed_at reward_reversed_at FROM account_referrals referral LEFT JOIN referral_rewards reward ON reward.referral_id=referral.id AND reward.beneficiary_account_id=$1 WHERE referral.referrer_account_id=$1 OR referral.referred_account_id=$1 ORDER BY referral.claimed_at,referral.id`,[actor.accountId])
    ]);
    return{exportVersion:1,exportedAt:new Date().toISOString(),classification:DATA_CLASSIFICATION,account:account.rows[0],memberships:memberships.rows,workspaceMemberships:workspaceMemberships.rows,sessions:sessions.rows,invitations:invitations.rows,credentials:tokens.rows,personalWorkflows:workflows.rows,auditEvents:audit.rows,referrals:referrals.rows};
  });}

  async deleteAccount(actor:AuthenticatedSession,correlationId:string):Promise<{requestId:string;completedAt:string;summary:Record<string,number>}>{return this.transaction("privacy_service",async client=>{
    const account=await client.query<{primary_email:string}>(`SELECT primary_email FROM accounts WHERE id=$1 AND deleted_at IS NULL FOR UPDATE`,[actor.accountId]);if(!account.rowCount)throw new DomainError("account_not_found","Account is unavailable or already deleted.",404);
    const owned=await client.query(`SELECT 1 FROM memberships membership JOIN roles role ON role.id=membership.role_id WHERE membership.account_id=$1 AND role.role_key='owner' AND membership.status='active'`,[actor.accountId]);if(owned.rowCount)throw new DomainError("ownership_transfer_required","Transfer or delete owned organisations before deleting the account.",409);
    const soleServiceOwner=await client.query(`SELECT 1 FROM service_account_owners owner JOIN service_accounts service ON service.id=owner.service_account_id WHERE owner.account_id=$1 AND service.status<>'revoked' AND NOT EXISTS(SELECT 1 FROM service_account_owners other WHERE other.service_account_id=owner.service_account_id AND other.account_id<>$1)`,[actor.accountId]);if(soleServiceOwner.rowCount)throw new DomainError("service_account_ownership_transfer_required","Assign another human owner or revoke owned service accounts before deleting the account.",409);
    const summary:Record<string,number>={};
    summary.sessions=(await client.query(`DELETE FROM account_sessions WHERE account_id=$1`,[actor.accountId])).rowCount??0;
    summary.credentials=(await client.query(`UPDATE access_tokens SET revoked_at=COALESCE(revoked_at,now()),revocation_reason=COALESCE(revocation_reason,'account_deleted') WHERE owner_account_id=$1 AND revoked_at IS NULL`,[actor.accountId])).rowCount??0;
    const personalWorkflowIds=(await client.query<{id:string}>(`SELECT id FROM synced_workflows WHERE owner_type='personal' AND owner_id=$1`,[actor.accountId])).rows.map(row=>row.id);summary.personalWorkflows=personalWorkflowIds.length;if(personalWorkflowIds.length){await client.query(`UPDATE workflow_revisions SET encrypted_payload=gen_random_bytes(32),payload_key_envelope=gen_random_bytes(32),searchable_metadata='{}',change_summary='' WHERE workflow_id=ANY($1::uuid[])`,[personalWorkflowIds]);await client.query(`UPDATE synced_workflows SET deleted_at=COALESCE(deleted_at,now()),name='Deleted workflow' WHERE id=ANY($1::uuid[])`,[personalWorkflowIds]);}
    summary.workspaceMemberships=(await client.query(`DELETE FROM workspace_memberships WHERE account_id=$1`,[actor.accountId])).rowCount??0;
    summary.organisationMemberships=(await client.query(`DELETE FROM memberships WHERE account_id=$1`,[actor.accountId])).rowCount??0;
    summary.serviceAccountOwnerships=(await client.query(`DELETE FROM service_account_owners WHERE account_id=$1`,[actor.accountId])).rowCount??0;
    await client.query(`UPDATE invitations SET email=concat('deleted+',id,'@invalid.local') WHERE accepted_by=$1 OR lower(email)=lower($2)`,[actor.accountId,account.rows[0].primary_email]);
    await client.query(`UPDATE runners SET status='revoked',revoked_at=COALESCE(revoked_at,now()) WHERE account_id=$1`,[actor.accountId]);
    const completedAt=new Date(),requestId=randomUUID();await client.query(`UPDATE accounts SET deleted_at=$2,identity_subject=concat('deleted:',id),primary_email=concat('deleted+',id,'@invalid.local'),email_verified=false,display_name='Deleted account' WHERE id=$1`,[actor.accountId,completedAt]);
    await client.query(`INSERT INTO privacy_deletion_requests(id,account_id,requested_at,completed_at,status,deletion_summary,correlation_id) VALUES($1,$2,$3,$3,'completed',$4,$5)`,[requestId,actor.accountId,completedAt,summary,correlationId]);
    return{requestId,completedAt:completedAt.toISOString(),summary};
  });}

  async runRetentionSweep(now=new Date(),limitPerClass=1000,onlyWorkspaceId:string|null=null):Promise<RetentionSweepResult>{return this.transaction("privacy_retention_worker",async client=>{
    const policies=await client.query<PolicyRow&{workspace_id:string}>(`SELECT workspace.id workspace_id,COALESCE(policy.execution_detail_days,90) execution_detail_days,COALESCE(policy.queue_event_days,30) queue_event_days,COALESCE(policy.webhook_delivery_days,7) webhook_delivery_days,COALESCE(policy.runner_command_days,30) runner_command_days,COALESCE(policy.audit_event_days,2555) audit_event_days,NULL::uuid changed_by,NULL::timestamptz changed_at FROM workspaces workspace LEFT JOIN workspace_data_retention policy ON policy.workspace_id=workspace.id WHERE workspace.deleted_at IS NULL AND ($1::uuid IS NULL OR workspace.id=$1)`,[onlyWorkspaceId]),result:RetentionSweepResult={workspaces:0,executionDetails:0,queueEvents:0,webhookDeliveries:0,runnerCommands:0,auditEvents:0,operationalEvidence:0},limit=Math.min(Math.max(limitPerClass,1),10000);
    for(const policy of policies.rows){result.workspaces++;const executionCutoff=new Date(now.getTime()-policy.execution_detail_days*86_400_000),queueCutoff=new Date(now.getTime()-policy.queue_event_days*86_400_000),webhookCutoff=new Date(now.getTime()-policy.webhook_delivery_days*86_400_000),commandCutoff=new Date(now.getTime()-policy.runner_command_days*86_400_000),auditCutoff=new Date(now.getTime()-policy.audit_event_days*86_400_000);
      const executionIds=(await client.query<{id:string}>(`SELECT id FROM executions WHERE workspace_id=$1 AND completed_at<$2 AND status IN ('succeeded','failed','timed_out','skipped','cancelled','expired') ORDER BY completed_at LIMIT $3`,[policy.workspace_id,executionCutoff,limit])).rows.map(row=>row.id);if(executionIds.length){await client.query(`DELETE FROM execution_checkpoints WHERE execution_id=ANY($1::uuid[])`,[executionIds]);await client.query(`DELETE FROM execution_events WHERE execution_id=ANY($1::uuid[])`,[executionIds]);await client.query(`UPDATE executions SET recovery_detail=NULL,interrupted_node=NULL,plugin_versions='[]',connection_references='[]',routing_requirements='{}',encrypted_payload_reference='retained://purged' WHERE id=ANY($1::uuid[])`,[executionIds]);result.executionDetails+=executionIds.length;}
      await client.query(`DELETE FROM queue_replays WHERE id IN(SELECT replay.id FROM queue_replays replay JOIN queued_events event ON event.id=replay.original_queue_event_id WHERE event.workspace_id=$1 AND event.created_at<$2 LIMIT $3)`,[policy.workspace_id,queueCutoff,limit]);result.queueEvents+=(await client.query(`DELETE FROM queued_events WHERE id IN(SELECT id FROM queued_events WHERE workspace_id=$1 AND created_at<$2 AND status IN ('completed','expired','dead_letter') ORDER BY created_at LIMIT $3)`,[policy.workspace_id,queueCutoff,limit])).rowCount??0;
      result.webhookDeliveries+=(await client.query(`DELETE FROM webhook_deliveries WHERE id IN(SELECT id FROM webhook_deliveries WHERE workspace_id=$1 AND (expires_at<=$2 OR received_at<$3) ORDER BY received_at LIMIT $4)`,[policy.workspace_id,now,webhookCutoff,limit])).rowCount??0;
      result.runnerCommands+=(await client.query(`DELETE FROM runner_commands WHERE id IN(SELECT id FROM runner_commands WHERE workspace_id=$1 AND created_at<$2 AND status IN ('rejected','completed','expired') ORDER BY created_at LIMIT $3)`,[policy.workspace_id,commandCutoff,limit])).rowCount??0;
      result.auditEvents+=(await client.query(`DELETE FROM audit_events WHERE id IN(SELECT id FROM audit_events WHERE workspace_id=$1 AND occurred_at<$2 ORDER BY occurred_at LIMIT $3)`,[policy.workspace_id,auditCutoff,limit])).rowCount??0;
    }if(onlyWorkspaceId===null){const securityCutoff=new Date(now.getTime()-2555*86_400_000),supportCutoff=new Date(now.getTime()-730*86_400_000);const supportIds=(await client.query<{id:string}>(`SELECT id FROM support_access_requests WHERE requested_until<$1 AND status IN ('approved','rejected','revoked') ORDER BY requested_until LIMIT $2`,[supportCutoff,limit])).rows.map(row=>row.id);if(supportIds.length){await client.query(`DELETE FROM support_access_events WHERE request_id=ANY($1::uuid[])`,[supportIds]);result.operationalEvidence+=(await client.query(`DELETE FROM support_access_requests WHERE id=ANY($1::uuid[])`,[supportIds])).rowCount??0;}const incidentIds=(await client.query<{id:string}>(`SELECT id FROM operational_incidents WHERE status='reviewed' AND reviewed_at<$1 ORDER BY reviewed_at LIMIT $2`,[securityCutoff,limit])).rows.map(row=>row.id);if(incidentIds.length){await client.query(`DELETE FROM operational_incident_events WHERE incident_id=ANY($1::uuid[])`,[incidentIds]);result.operationalEvidence+=(await client.query(`DELETE FROM operational_incidents WHERE id=ANY($1::uuid[])`,[incidentIds])).rowCount??0;}result.operationalEvidence+=(await client.query(`DELETE FROM service_account_access_reviews WHERE id IN(SELECT id FROM service_account_access_reviews WHERE status IN ('retained','revoked') AND decided_at<$1 ORDER BY decided_at LIMIT $2)`,[securityCutoff,limit])).rowCount??0;result.operationalEvidence+=(await client.query(`DELETE FROM privacy_deletion_requests WHERE id IN(SELECT id FROM privacy_deletion_requests WHERE completed_at<$1 ORDER BY completed_at LIMIT $2)`,[securityCutoff,limit])).rowCount??0;}return result;
  });}

  private async transaction<T>(role:"privacy_service"|"privacy_retention_worker",operation:(client:PoolClient)=>Promise<T>):Promise<T>{const client=await this.pool.connect();try{await client.query("BEGIN");await client.query(`SELECT set_config('app.system_role',$1,true)`,[role]);const result=await operation(client);await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
}

export function validateRetentionPolicy(policy:Omit<WorkspaceRetentionPolicy,"changedBy"|"changedAt">):void{const bounds:Array<[keyof typeof policy,number,number]>=[["executionDetailDays",1,3650],["queueEventDays",1,365],["webhookDeliveryDays",1,30],["runnerCommandDays",1,365],["auditEventDays",365,3650]];for(const[key,min,max]of bounds)if(!Number.isInteger(policy[key])||policy[key]<min||policy[key]>max)throw new DomainError("retention_policy_invalid",`${key} must be between ${min} and ${max} days.`);}
function policyFromRow(row:PolicyRow):WorkspaceRetentionPolicy{return{executionDetailDays:row.execution_detail_days,queueEventDays:row.queue_event_days,webhookDeliveryDays:row.webhook_delivery_days,runnerCommandDays:row.runner_command_days,auditEventDays:row.audit_event_days,changedBy:row.changed_by,changedAt:row.changed_at?.toISOString()??null};}
function notFound():never{throw new DomainError("workspace_not_found","Workspace was not found.",404);}
