import { RUNNER_PROTOCOL_VERSION,type RunnerIdentity,type RunnerRequirements } from "@sandbox/contracts";
import { describe,expect,it } from "vitest";
import { selectRunnerFromPool,type RunnerPoolCandidate,type RunnerPoolPolicy } from "./runner_pool.js";

const workspaceId="10000000-0000-4000-8000-000000000001",environmentId="20000000-0000-4000-8000-000000000002",now=new Date("2026-08-27T12:00:00.000Z");
const requirements:RunnerRequirements={protocolVersion:RUNNER_PROTOCOL_VERSION,engineVersion:"0.4.0",pluginRuntimeVersion:"0.4.0",runnerTypes:["self_hosted_server"],architectures:["x86_64"],workspaceId,environmentId,region:"eu-west-2",requiredTags:[],capabilities:[],plugins:[],connectionIds:[],minimumAvailableConcurrency:1};
const policy:RunnerPoolPolicy={strategy:"least_loaded",region:"eu-west-2",requiredTags:["production"],maximumConcurrency:10,staleAfterSeconds:90};
function candidate(index:number,overrides:Partial<RunnerPoolCandidate>={}):RunnerPoolCandidate{const identity:RunnerIdentity={runnerId:`30000000-0000-4000-8000-00000000000${index}`,keyId:`device-${index}`,runnerType:"self_hosted_server",protocolVersion:RUNNER_PROTOCOL_VERSION,engineVersion:"0.4.0",pluginRuntimeVersion:"0.4.0",architecture:"x86_64",operatingSystem:"linux",workspaceId,environmentId,region:"eu-west-2",tags:["production"],concurrencyLimit:4,maintenanceState:"active",nodeCapabilities:[],plugins:[],connections:[]};return{identity,currentWorkload:0,lastSeenAt:"2026-08-27T11:59:45.000Z",online:true,enabled:true,priority:100,...overrides};}

describe("runner pool selection",()=>{
  it("selects the lowest proportional load with a deterministic tie break",()=>{const selected=selectRunnerFromPool(policy,requirements,[candidate(2,{currentWorkload:2}),candidate(1,{currentWorkload:1})],0,now);expect(selected.runner?.identity.runnerId).toBe(candidate(1).identity.runnerId);});
  it("uses priority before load for failover pools",()=>{const selected=selectRunnerFromPool({...policy,strategy:"priority_failover"},requirements,[candidate(1,{priority:200,currentWorkload:0}),candidate(2,{priority:10,currentWorkload:3})],0,now);expect(selected.runner?.identity.runnerId).toBe(candidate(2).identity.runnerId);});
  it("round robins only across compatible live members",()=>{const stale=candidate(3,{lastSeenAt:"2026-08-27T11:00:00.000Z"});const first=selectRunnerFromPool({...policy,strategy:"round_robin"},requirements,[candidate(1),stale,candidate(2)],0,now),second=selectRunnerFromPool({...policy,strategy:"round_robin"},requirements,[candidate(1),stale,candidate(2)],first.nextCursor,now);expect([first.runner?.identity.runnerId,second.runner?.identity.runnerId]).toEqual([candidate(1).identity.runnerId,candidate(2).identity.runnerId]);expect(first.rejected[0]).toMatchObject({runnerId:stale.identity.runnerId,reasons:["Runner heartbeat is stale."]});});
  it("reserves requested capacity under the aggregate pool limit",()=>{const selected=selectRunnerFromPool({...policy,maximumConcurrency:4},requirements,[candidate(1,{currentWorkload:2}),candidate(2,{currentWorkload:1})],0,now);expect(selected.runner).not.toBeNull();expect(selectRunnerFromPool({...policy,maximumConcurrency:3},requirements,[candidate(1,{currentWorkload:2}),candidate(2,{currentWorkload:1})],0,now).runner).toBeNull();expect(selectRunnerFromPool({...policy,maximumConcurrency:4}, {...requirements,minimumAvailableConcurrency:2},[candidate(1,{currentWorkload:2}),candidate(2,{currentWorkload:1})],0,now).runner).toBeNull();});
  it("uses available rather than configured concurrency",()=>{const selected=selectRunnerFromPool(policy,{...requirements,minimumAvailableConcurrency:2},[candidate(1,{currentWorkload:3})],0,now);expect(selected.runner).toBeNull();expect(selected.rejected[0].reasons).toContain("Runner has insufficient available concurrency.");});
  it("rejects a runner that misses pool placement even when workflow-compatible",()=>{const wrong=candidate(1,{identity:{...candidate(1).identity,tags:[]}});const selected=selectRunnerFromPool(policy,requirements,[wrong],0,now);expect(selected.runner).toBeNull();expect(selected.rejected[0].reasons).toContain("Missing pool tag production.");});
});
