import type { DocPage } from "./content";

type DraftPage = Omit<DocPage, "version" | "reviewed"> &
  Partial<Pick<DocPage, "version" | "reviewed">>;

const guide = (page: DraftPage): DocPage => ({
  version: "0.7.1-beta.3",
  reviewed: "2026-08-28",
  ...page,
});

export const expandedDocs: DocPage[] = [
  guide({
    slug: "getting-started/quick-tour",
    section: "Getting Started",
    title: "Take the product tour",
    description: "Learn the four surfaces you use to build, test, publish and explain an automation.",
    prerequisites: ["Sandbox desktop app installed"],
    concepts: [
      { title: "Canvas", body: "The editable graph where triggers, actions and branches become a workflow." },
      { title: "Inspector", body: "The configuration and run-data panel for the selected node." },
      { title: "Execution history", body: "An immutable timeline of attempts, outputs and state changes." },
    ],
    steps: [
      { title: "Open a workflow", body: "Choose a template or an existing draft, then identify its trigger and terminal actions." },
      { title: "Follow the graph", body: "Select each node in order. The inspector shows configuration separately from resolved run data." },
      { title: "Run in preview", body: "Start a manual test and watch the active path move across the canvas." },
      { title: "Open the execution", body: "Use the completed run to inspect duration, attempts and the bounded output of every node." },
    ],
    result: "You can move confidently between editing a workflow and explaining a completed run.",
    errors: ["A draft is editable; a published revision is not. Create a new draft before changing a deployed workflow."],
    related: ["getting-started/first-workflow", "workflows/editor", "getting-started/understand-executions"],
  }),
  guide({
    slug: "getting-started/import-workflow",
    section: "Getting Started",
    title: "Import a workflow",
    description: "Review an exported workflow before it can access connections, files or a runner.",
    prerequisites: ["A Sandbox workflow export", "Permission to create workflows in the target workspace"],
    concepts: [
      { title: "Portable definition", body: "The graph and non-secret configuration can move between workspaces." },
      { title: "Local binding", body: "Connections, folders and runners must be selected again in the destination." },
    ],
    notes: ["Imports never include credential values or a browser profile's stored session."],
    steps: [
      { title: "Inspect the source", body: "Confirm who supplied the export and review its declared node types and capabilities." },
      { title: "Import as a draft", body: "Choose Import workflow, select the file and keep the workflow disabled while validation runs." },
      { title: "Resolve dependencies", body: "Map missing connections, approved folders and runner labels to resources in this workspace." },
      { title: "Test every branch", body: "Run with representative sample data before publishing a destination-specific revision." },
    ],
    result: "The imported workflow is a reviewed draft with explicit local resource bindings.",
    errors: ["Unknown node types remain unresolved until their plugin is installed.", "A connection name may match while its permissions do not; verify scopes explicitly."],
    related: ["workflows/revisions-and-publishing", "workflows/permissions", "plugins/permissions"],
  }),

  guide({
    slug: "workflows/editor",
    section: "Workflows",
    title: "Use the workflow editor",
    description: "Build readable automation graphs with deliberate inputs, outputs and failure paths.",
    prerequisites: ["A workflow draft"],
    concepts: [
      { title: "Node", body: "One trigger, action or control-flow decision with a typed contract." },
      { title: "Connection", body: "A directional edge that passes control and available data to the next node." },
      { title: "Draft", body: "The mutable working copy that is separate from the last published revision." },
    ],
    steps: [
      { title: "Place the trigger", body: "Start with exactly one entry condition so the execution boundary is obvious." },
      { title: "Add the smallest useful actions", body: "Name nodes by intent, keep transformations close to their consumer and avoid long implicit chains." },
      { title: "Connect failure paths", body: "Decide which errors stop the run, which retry and which continue to an explicit recovery branch." },
      { title: "Validate the graph", body: "Resolve missing fields, disconnected nodes and incompatible data mappings before running." },
    ],
    result: "The canvas communicates what starts the workflow, what it changes and how it can stop.",
    errors: ["Cycles are rejected unless a dedicated bounded loop node owns the iteration.", "Deleting an upstream node invalidates mappings that read from its output."],
    related: ["workflows/variables-and-data", "workflows/branches-and-conditions", "workflows/revisions-and-publishing"],
  }),
  guide({
    slug: "workflows/variables-and-data",
    section: "Workflows",
    title: "Map variables and node data",
    description: "Pass typed values between nodes without hiding where a field came from.",
    concepts: [
      { title: "Run input", body: "Data supplied by the trigger when an execution begins." },
      { title: "Node output", body: "Bounded data produced by a completed node and available downstream." },
      { title: "Expression", body: "A small read-only mapping that selects or formats available values." },
    ],
    notes: ["A variable reference records its source node, making later execution inspection easier."],
    steps: [
      { title: "Open the field mapper", body: "Select an input field and switch from a literal value to workflow data." },
      { title: "Choose a source", body: "Select trigger data or a preceding node, then choose a field from its typed output." },
      { title: "Handle missing values", body: "Add a default only when it is safe; otherwise validate and fail with a useful message." },
      { title: "Preview with sample data", body: "Inspect the resolved value before executing the action." },
    ],
    result: "Every dynamic input can be traced back to a specific trigger field or node output.",
    errors: ["A downstream node cannot read data from a branch that did not run.", "Secret values are masked in previews and logs."],
    related: ["workflows/editor", "workflows/branches-and-conditions", "files-and-data/json"],
  }),
  guide({
    slug: "workflows/branches-and-conditions",
    section: "Workflows",
    title: "Build branches and conditions",
    description: "Route an execution with testable rules and an intentional fallback path.",
    concepts: [
      { title: "Condition", body: "A typed comparison evaluated against data already available to the node." },
      { title: "Fallback", body: "The branch taken when no earlier condition matches." },
    ],
    steps: [
      { title: "Define the decision", body: "Name the branch node after the business question it answers." },
      { title: "Order specific cases first", body: "Place narrow conditions before broad matches and keep an explicit fallback." },
      { title: "Test boundaries", body: "Run values just below, at and above each threshold, including empty and malformed input." },
      { title: "Inspect skipped paths", body: "Confirm unselected branches are marked skipped rather than failed." },
    ],
    result: "Representative inputs select exactly one documented path and leave the remaining paths explainably skipped.",
    errors: ["Comparing text with a number requires an explicit conversion.", "An empty fallback can make a successful run appear to do nothing."],
    related: ["workflows/variables-and-data", "getting-started/understand-executions", "execution/failure-recovery"],
  }),
  guide({
    slug: "workflows/schedules-and-triggers",
    section: "Workflows",
    title: "Configure schedules and triggers",
    description: "Start workflows at predictable times or from deliberate manual and event inputs.",
    prerequisites: ["A tested workflow draft", "An online eligible runner for unattended schedules"],
    concepts: [
      { title: "Trigger", body: "The only entry point that creates an execution and its initial data." },
      { title: "Schedule timezone", body: "The named timezone used to evaluate future calendar occurrences." },
    ],
    steps: [
      { title: "Choose the trigger", body: "Use manual while developing; add a schedule only after the graph is stable." },
      { title: "Set timing explicitly", body: "Select frequency, timezone and the intended behaviour around daylight-saving changes." },
      { title: "Define overlap policy", body: "Choose whether a new occurrence queues, is skipped or replaces work already running." },
      { title: "Publish and observe", body: "Enable the schedule on a published revision, then verify the next calculated run time." },
    ],
    result: "The workflow shows its next occurrence, timezone and overlap behaviour before it runs unattended.",
    errors: ["Schedules do not run on an offline local runner.", "Editing a draft does not change the revision currently used by a schedule."],
    related: ["execution/concurrency-and-queues", "workflows/revisions-and-publishing", "execution/local-runner"],
  }),
  guide({
    slug: "workflows/permissions",
    section: "Workflows",
    title: "Review workflow permissions",
    description: "Understand the files, applications, domains and connections a revision can use before enabling it.",
    concepts: [
      { title: "Declared capability", body: "Access requested by a node or plugin and visible during review." },
      { title: "Resource binding", body: "A workspace-approved connection, folder or runner assigned to that capability." },
    ],
    steps: [
      { title: "Open the permission summary", body: "Review the combined capabilities of every reachable node in the draft." },
      { title: "Narrow each grant", body: "Bind exact folders, connection scopes and network domains instead of broad substitutes." },
      { title: "Compare with the published revision", body: "Treat new access as a material change that requires another review." },
      { title: "Test denied access", body: "Confirm the workflow fails safely when a resource is outside its approved boundary." },
    ],
    result: "The published revision has only the resources required by its reachable execution paths.",
    errors: ["A plugin update can add capabilities and therefore require re-approval.", "Runner operating-system access does not override a missing Sandbox grant."],
    related: ["teams-and-governance/approvals", "plugins/permissions", "troubleshooting/permissions"],
  }),
  guide({
    slug: "workflows/revisions-and-publishing",
    section: "Workflows",
    title: "Publish workflow revisions",
    description: "Turn a tested draft into an immutable revision that deployments can run safely.",
    prerequisites: ["A valid workflow draft", "Permission to publish in the workspace"],
    concepts: [
      { title: "Revision", body: "An immutable snapshot of graph, configuration and declared capabilities." },
      { title: "Deployment", body: "A revision assigned to a runner boundary and optional trigger configuration." },
    ],
    steps: [
      { title: "Review the change summary", body: "Compare nodes, mappings, connection bindings and permissions with the current revision." },
      { title: "Run the validation set", body: "Test happy paths, expected failures and each branch with non-sensitive fixtures." },
      { title: "Publish with context", body: "Describe the intent and expected operational impact of the revision." },
      { title: "Promote deliberately", body: "Assign the revision to the required environment and watch its first live execution." },
    ],
    result: "A traceable immutable revision is deployed without changing historical runs.",
    errors: ["Publishing fails while a referenced connection or plugin version is unavailable.", "Rolling back selects an earlier revision; it does not erase later revisions."],
    related: ["teams-and-governance/approvals", "teams-and-governance/environments", "getting-started/understand-executions"],
  }),

  guide({
    slug: "browser-automation/profiles-and-sessions",
    section: "Browser Automation",
    title: "Manage browser profiles",
    description: "Keep cookies and site sessions isolated from the personal browser on your computer.",
    prerequisites: ["Managed Chromium runtime installed"],
    concepts: [
      { title: "Managed profile", body: "A Sandbox-owned browser data directory with a clear workspace purpose." },
      { title: "Session boundary", body: "The point at which cookies, storage and authenticated state are reused or discarded." },
    ],
    notes: ["Use a dedicated site account when automation must sign in repeatedly; do not reuse a personal profile."],
    steps: [
      { title: "Create the profile", body: "Name it after the site and environment, then restrict its approved domains." },
      { title: "Sign in interactively", body: "Open the managed profile and complete the site's ordinary authentication flow." },
      { title: "Choose persistence", body: "Keep the session for trusted recurring work or reset it after sensitive one-off runs." },
      { title: "Test expiry", body: "Confirm the workflow's failure path when the site asks for authentication again." },
    ],
    result: "Automation uses an isolated, named session with a known renewal path.",
    errors: ["A profile locked by another active execution cannot be opened concurrently.", "Multifactor challenges may require a person and are never bypassed."],
    related: ["browser-automation/recorder", "browser-automation/forms-and-uploads", "troubleshooting/browser"],
  }),
  guide({
    slug: "browser-automation/forms-and-uploads",
    section: "Browser Automation",
    title: "Complete forms and upload files",
    description: "Fill browser forms predictably while keeping secrets and local files inside approved boundaries.",
    prerequisites: ["A managed browser profile", "Approved access to any upload folder"],
    concepts: [
      { title: "Sensitive field", body: "A field whose value comes from a protected connection and is never stored in the graph." },
      { title: "File binding", body: "An approved local or runner-side folder exposed to the workflow by label." },
    ],
    steps: [
      { title: "Map ordinary fields", body: "Use labels and roles to locate controls, then map typed workflow values." },
      { title: "Reference protected values", body: "Select a credential field from a connection instead of pasting it into the node." },
      { title: "Bind the upload", body: "Resolve the file from an approved folder and validate name, size and extension first." },
      { title: "Verify before submit", body: "Read back non-sensitive fields and confirm the intended document is displayed." },
    ],
    result: "The form is submitted with traceable non-secret inputs and an explicitly approved file.",
    errors: ["A site-generated file picker may require a direct input locator.", "Protected values are omitted from screenshots and execution output."],
    related: ["browser-automation/locators", "files-and-data/files-and-folders", "files-and-data/secrets-and-connections"],
  }),
  guide({
    slug: "browser-automation/downloads",
    section: "Browser Automation",
    title: "Handle browser downloads",
    description: "Wait for, validate and move downloaded files without guessing when the browser is finished.",
    prerequisites: ["An approved destination folder"],
    steps: [
      { title: "Declare the expected download", body: "Configure the action that starts the download with a timeout and optional filename pattern." },
      { title: "Wait for completion", body: "Use the browser download event; do not rely on a fixed delay or a temporary extension disappearing." },
      { title: "Validate the artifact", body: "Check MIME type, size and filename before passing the file downstream." },
      { title: "Move or transform", body: "Write the completed artifact to an approved folder using a deterministic conflict policy." },
    ],
    result: "Downstream nodes receive one complete, validated file and its metadata.",
    errors: ["Multiple downloads require a tighter filename or initiating-action match.", "A browser profile can download only into runner-accessible storage."],
    related: ["files-and-data/files-and-folders", "files-and-data/csv", "browser-automation/screenshots"],
  }),
  guide({
    slug: "browser-automation/screenshots",
    section: "Browser Automation",
    title: "Capture screenshots and evidence",
    description: "Collect useful visual evidence without exposing more browser content than a run needs.",
    concepts: [
      { title: "Failure evidence", body: "A bounded screenshot and page metadata captured when an action cannot continue." },
      { title: "Redaction", body: "Masking applied before evidence is retained or included in diagnostics." },
    ],
    steps: [
      { title: "Choose capture points", body: "Capture after meaningful state changes or on failure, not after every click." },
      { title: "Bound the frame", body: "Prefer the relevant element or viewport over a full-page capture." },
      { title: "Add redaction selectors", body: "Mask account identifiers, protected fields and other sensitive regions." },
      { title: "Set retention", body: "Keep evidence only as long as the workspace needs for operations or audit." },
    ],
    result: "A failed run has enough visual context to diagnose the page state without becoming a browser recording.",
    errors: ["Cross-origin frames may appear blank unless the browser can capture them safely.", "A changed page layout can invalidate redaction selectors; review evidence after site updates."],
    related: ["browser-automation/recorder", "execution/logs-and-evidence", "troubleshooting/diagnostic-bundles"],
  }),
  guide({
    slug: "browser-automation/frames-and-tabs",
    section: "Browser Automation",
    title: "Work with frames and tabs",
    description: "Keep browser context explicit when a task opens a new tab or embeds controls in a frame.",
    concepts: [
      { title: "Page context", body: "The active browser tab against which ordinary locators are evaluated." },
      { title: "Frame context", body: "A nested document that must be selected before locating its elements." },
    ],
    steps: [
      { title: "Wait for the context", body: "Match a new tab by its opener and expected URL, or a frame by stable identity." },
      { title: "Switch explicitly", body: "Add a context node before any action that targets the new document." },
      { title: "Perform the bounded action", body: "Use semantic locators inside that context and retain the same timeout policy." },
      { title: "Return or close", body: "Restore the original page deliberately so later nodes do not inherit ambiguous context." },
    ],
    result: "Every browser action runs against a named tab and frame rather than whichever page happens to be active.",
    errors: ["A frame reload invalidates handles captured from its previous document.", "Pop-up blocking can prevent a tab from opening outside a user-initiated action."],
    related: ["browser-automation/locators", "browser-automation/profiles-and-sessions", "browser-automation/troubleshooting"],
  }),
  guide({
    slug: "browser-automation/troubleshooting",
    section: "Browser Automation",
    title: "Troubleshoot browser actions",
    description: "Diagnose the page, context and locator before increasing waits or adding retries.",
    steps: [
      { title: "Inspect the failure frame", body: "Open the screenshot, URL and page title captured at the first failed browser node." },
      { title: "Confirm context", body: "Check the expected tab, frame, managed profile and authentication state." },
      { title: "Re-test the locator", body: "Prefer a stable role or label and verify it resolves to one visible actionable element." },
      { title: "Adjust timing last", body: "Wait for a meaningful page condition instead of inserting a fixed sleep." },
    ],
    result: "The corrected action is tied to a page condition or locator that explains when it can proceed.",
    errors: ["Repeated authentication redirects usually indicate an expired managed session.", "A CAPTCHA requires a supported human checkpoint or a different integration path."],
    related: ["browser-automation/locators", "browser-automation/screenshots", "troubleshooting/browser"],
  }),

  guide({
    slug: "files-and-data/files-and-folders",
    section: "Files and Data",
    title: "Work with files and folders",
    description: "Read and write files through named roots with predictable conflict and cleanup behaviour.",
    concepts: [
      { title: "Approved root", body: "A folder exposed to a workflow under a stable label rather than an arbitrary absolute path." },
      { title: "Conflict policy", body: "The declared choice to fail, replace or create a unique name when output exists." },
    ],
    steps: [
      { title: "Bind a root", body: "Select the smallest folder the workflow needs and give it an environment-neutral label." },
      { title: "Resolve a relative path", body: "Build paths from validated segments and reject parent-directory traversal." },
      { title: "Validate before reading", body: "Check that the entry is a file and enforce expected size and type boundaries." },
      { title: "Write atomically", body: "Choose a conflict policy and expose the final path as node output." },
    ],
    result: "The workflow accesses only paths below its approved root and reports the exact artifact it produced.",
    errors: ["Absolute paths are not portable between local and self-hosted runners.", "A file opened by another application may be temporarily unavailable for replacement."],
    related: ["files-and-data/csv", "files-and-data/json", "workflows/permissions"],
  }),
  guide({
    slug: "files-and-data/csv",
    section: "Files and Data",
    title: "Read and write CSV data",
    description: "Turn tabular files into predictable records while handling headers, encodings and malformed rows.",
    prerequisites: ["An input file inside an approved folder"],
    steps: [
      { title: "Declare the dialect", body: "Set encoding, delimiter, quote character and whether the first row contains headers." },
      { title: "Define the columns", body: "Map source headers to stable field names and choose the expected type for each value." },
      { title: "Choose row-error behaviour", body: "Fail on the first invalid row or collect bounded row errors for review." },
      { title: "Write deterministic output", body: "Preserve a fixed column order and line-ending policy when creating a new file." },
    ],
    result: "Each valid row becomes a typed record and invalid rows are explained with their line number.",
    errors: ["A byte-order mark can change how an unspecified encoding is detected.", "Header names that differ only by case must be mapped explicitly."],
    related: ["files-and-data/files-and-folders", "workflows/variables-and-data", "reference/limits"],
  }),
  guide({
    slug: "files-and-data/json",
    section: "Files and Data",
    title: "Transform JSON",
    description: "Select, validate and reshape structured data without losing the source of each value.",
    concepts: [
      { title: "Schema", body: "The expected structure and types used to reject ambiguous downstream data." },
      { title: "Projection", body: "A new object containing only the fields the next step needs." },
    ],
    steps: [
      { title: "Parse the source", body: "Read JSON from a file, HTTP response or preceding node and set a maximum accepted size." },
      { title: "Validate structure", body: "Require important fields, distinguish null from missing and reject unexpected types." },
      { title: "Project the result", body: "Map only needed values into a smaller named object." },
      { title: "Inspect sample output", body: "Run with representative data, including an empty collection and a missing optional field." },
    ],
    result: "Downstream nodes receive a smaller validated value with predictable fields.",
    errors: ["A path returning multiple values cannot be assigned to a scalar field.", "Large arrays should be processed in bounded batches."],
    related: ["workflows/variables-and-data", "files-and-data/http-requests", "reference/data-types"],
  }),
  guide({
    slug: "files-and-data/http-requests",
    section: "Files and Data",
    title: "Make HTTP requests",
    description: "Call an approved HTTPS endpoint with explicit authentication, timeouts and response validation.",
    prerequisites: ["The target domain approved for the workflow", "A connection when authentication is required"],
    concepts: [
      { title: "Connection", body: "A protected workspace resource that supplies authentication without exposing its value." },
      { title: "Idempotent request", body: "A request that can be repeated without creating unintended additional effects." },
    ],
    steps: [
      { title: "Choose method and URL", body: "Use HTTPS, a fixed approved host and path parameters derived from validated values." },
      { title: "Attach authentication", body: "Select a connection field for the required header instead of constructing credentials in the workflow." },
      { title: "Set boundaries", body: "Configure connect and response timeouts, maximum body size and accepted status codes." },
      { title: "Validate the response", body: "Check content type and structure before mapping data downstream." },
    ],
    result: "The workflow accepts only the expected response and exposes a bounded parsed output.",
    errors: ["Redirects to an unapproved domain are blocked.", "Retrying a write request without idempotency can duplicate an external action."],
    related: ["files-and-data/secrets-and-connections", "execution/retries", "files-and-data/json"],
  }),
  guide({
    slug: "files-and-data/secrets-and-connections",
    section: "Files and Data",
    title: "Use secrets and connections",
    description: "Keep protected values out of workflow definitions, logs and exported files.",
    concepts: [
      { title: "Connection", body: "A named set of protected fields with scopes and workspace ownership." },
      { title: "Secret reference", body: "A pointer resolved only by an authorised runner when the node executes." },
    ],
    notes: ["The editor can show that a protected field is configured, but it cannot reveal the stored value."],
    steps: [
      { title: "Create the connection", body: "Choose the provider or generic credential type and enter the value through the protected form." },
      { title: "Limit its use", body: "Assign the connection to the required workspace and workflows, with the narrowest available scopes." },
      { title: "Reference a field", body: "Map the protected value directly into a node input marked sensitive." },
      { title: "Rotate safely", body: "Update the connection, test a draft and retire the previous credential according to provider policy." },
    ],
    result: "The workflow can authenticate without containing, printing or exporting the credential value.",
    errors: ["Copying a secret into an ordinary text field bypasses masking and must be removed.", "A connection unavailable to the selected runner environment fails before the action starts."],
    related: ["workflows/permissions", "teams-and-governance/environments", "troubleshooting/permissions"],
  }),

  guide({
    slug: "execution/local-runner",
    section: "Execution",
    title: "Local runner",
    description: "Understand availability, access and lifecycle when workflows run on this computer.",
    prerequisites: ["Sandbox desktop app installed and signed in"],
    concepts: [
      { title: "Execution boundary", body: "The device on which node code receives its approved file, application and network access." },
      { title: "Heartbeat", body: "The runner status signal used to decide whether scheduled work can be assigned." },
    ],
    steps: [
      { title: "Pair the desktop", body: "Confirm the workspace and device identity shown by the application." },
      { title: "Grant local resources", body: "Approve named folders and applications required by the workflow." },
      { title: "Run a preflight", body: "Check the runner version, free space and reachability of private targets." },
      { title: "Keep it available", body: "Leave the desktop runner running for schedules and review its sleep behaviour." },
    ],
    result: "The workflow runs on the intended computer with an explicit set of local resources.",
    errors: ["Sleeping, signing out or quitting the runner prevents new local executions.", "Operating-system permission changes can invalidate an existing folder grant."],
    related: ["getting-started/run-locally", "execution/concurrency-and-queues", "troubleshooting/runner"],
  }),
  guide({
    slug: "execution/retries",
    section: "Execution",
    title: "Configure retries and timeouts",
    description: "Retry temporary failures without multiplying side effects or hiding a persistent error.",
    concepts: [
      { title: "Attempt", body: "One bounded invocation of a node within an execution." },
      { title: "Backoff", body: "The increasing delay before another eligible attempt." },
      { title: "Timeout", body: "The maximum duration allowed for an attempt before it is cancelled." },
    ],
    steps: [
      { title: "Classify the action", body: "Decide whether repeating it is read-only, idempotent or capable of duplicate side effects." },
      { title: "Choose retryable errors", body: "Retry explicit temporary conditions such as a timeout or throttling response, not validation failures." },
      { title: "Set a small budget", body: "Configure attempts, backoff and an overall deadline appropriate to the external system." },
      { title: "Test exhaustion", body: "Force a temporary failure and verify the final error reaches the intended recovery path." },
    ],
    result: "Temporary errors get a bounded second chance and permanent errors fail quickly with their original cause.",
    errors: ["A node with external side effects should use an idempotency key before retries are enabled.", "A workflow deadline can expire before a node uses its complete retry budget."],
    related: ["execution/failure-recovery", "files-and-data/http-requests", "developers/idempotency-and-rate-limits"],
  }),
  guide({
    slug: "execution/failure-recovery",
    section: "Execution",
    title: "Design failure recovery",
    description: "Make partial work visible and choose whether to compensate, continue or stop.",
    concepts: [
      { title: "Recovery path", body: "An explicit branch entered after a handled node failure." },
      { title: "Compensation", body: "A deliberate action that reverses or records earlier side effects when full rollback is impossible." },
    ],
    steps: [
      { title: "List side effects", body: "Identify every node that changes a file, browser site or external service." },
      { title: "Choose the safe stop point", body: "Fail before irreversible work whenever validation can happen earlier." },
      { title: "Add recovery", body: "Record context, notify an owner or compensate only when the action is reliable and authorised." },
      { title: "Rehearse partial failure", body: "Interrupt each side-effecting stage and confirm a rerun cannot silently duplicate work." },
    ],
    result: "A failed execution leaves a documented state and a clear next action for an operator.",
    errors: ["Continuing after an unknown side effect can corrupt later assumptions.", "Compensation is another side effect and needs its own failure handling."],
    related: ["execution/retries", "getting-started/understand-executions", "teams-and-governance/approvals"],
  }),
  guide({
    slug: "execution/concurrency-and-queues",
    section: "Execution",
    title: "Manage concurrency and queues",
    description: "Control how overlapping executions share runners and external resources.",
    concepts: [
      { title: "Concurrency limit", body: "The maximum number of eligible executions that may run at the same time." },
      { title: "Queue", body: "Ordered pending work waiting for compatible capacity and policy." },
    ],
    steps: [
      { title: "Find shared resources", body: "Identify browser profiles, files and APIs that cannot safely handle simultaneous access." },
      { title: "Set limits", body: "Apply the narrowest workflow or runner-pool limit that protects those resources." },
      { title: "Choose an overlap policy", body: "Queue important occurrences and skip replaceable ones such as frequent refresh jobs." },
      { title: "Watch queue age", body: "Alert when work waits longer than its useful completion window." },
    ],
    result: "Executions use available capacity without contending for a single-session resource.",
    errors: ["A queue with no compatible online runner cannot make progress.", "Higher concurrency may increase external throttling rather than throughput."],
    related: ["workflows/schedules-and-triggers", "execution/runner-pools", "developers/idempotency-and-rate-limits"],
  }),
  guide({
    slug: "execution/logs-and-evidence",
    section: "Execution",
    title: "Read logs and evidence",
    description: "Use structured events, node output and redacted artifacts to explain what happened.",
    concepts: [
      { title: "Structured event", body: "A timestamped execution fact with node, attempt, severity and correlation context." },
      { title: "Artifact", body: "A bounded file or screenshot intentionally retained with a run." },
    ],
    steps: [
      { title: "Start at the timeline", body: "Find the first failed node and its attempt rather than reading all messages chronologically." },
      { title: "Compare input and output", body: "Check resolved non-secret input, bounded output and duration for that attempt." },
      { title: "Open relevant evidence", body: "Review only the screenshot or artifact attached to the failing state transition." },
      { title: "Export with care", body: "Preview redactions and retention before sharing diagnostics outside the workspace." },
    ],
    result: "The cause of a run is supported by the smallest relevant set of structured evidence.",
    errors: ["Large outputs and log messages are truncated at documented limits.", "Protected values remain masked even for workspace administrators."],
    related: ["getting-started/understand-executions", "browser-automation/screenshots", "troubleshooting/diagnostic-bundles"],
  }),

  guide({
    slug: "plugins/manifest",
    section: "Plugins",
    title: "Plugin manifest",
    description: "Describe plugin identity, nodes, versions and required capabilities in one reviewable contract.",
    prerequisites: ["A Plugin SDK project"],
    concepts: [
      { title: "Node contract", body: "The typed inputs, outputs and presentation metadata exposed to workflow authors." },
      { title: "Capability", body: "A host-mediated operation the guest component may request at runtime." },
    ],
    steps: [
      { title: "Set immutable identity", body: "Choose a package identifier and use semantic versions for published changes." },
      { title: "Describe each node", body: "Provide clear names, bounded schemas and documentation for inputs, outputs and errors." },
      { title: "Declare capabilities", body: "List only the domains and host operations reachable by the implementation." },
      { title: "Validate the package", body: "Run schema and integrity checks before installing it into a development workspace.", code: "sandbox-plugin validate" },
    ],
    result: "The host can present and review the plugin without executing its guest code.",
    errors: ["A package identifier cannot be changed after publication.", "A node implementation cannot invoke an undeclared host capability."],
    related: ["plugins/sdk-setup", "plugins/permissions", "plugins/publishing"],
  }),
  guide({
    slug: "plugins/permissions",
    section: "Plugins",
    title: "Plugin permissions",
    description: "Design plugin capabilities so an administrator can understand and constrain runtime access.",
    concepts: [
      { title: "Guest component", body: "Plugin code that runs without ambient host access." },
      { title: "Capability broker", body: "The host boundary that validates an approved request before performing it." },
    ],
    steps: [
      { title: "Inventory host interactions", body: "List network, storage, time and protected-value operations for each node." },
      { title: "Declare narrow scopes", body: "Use specific operations and domain patterns instead of a general network or filesystem grant." },
      { title: "Handle denial", body: "Return a useful typed error when the workspace refuses or removes a capability." },
      { title: "Review updates", body: "Call out newly requested access as part of the version change." },
    ],
    result: "Every privileged plugin operation passes through a visible, revocable host grant.",
    errors: ["Undeclared access is denied regardless of the runner's operating-system permissions.", "A capability increase can pause existing workflow deployments for review."],
    related: ["plugins/manifest", "workflows/permissions", "teams-and-governance/approvals"],
  }),
  guide({
    slug: "plugins/publishing",
    section: "Plugins",
    title: "Package and publish a plugin",
    description: "Produce a reproducible signed package with useful documentation and upgrade notes.",
    prerequisites: ["A valid plugin manifest", "Passing package tests", "Publisher access to the destination registry"],
    steps: [
      { title: "Build reproducibly", body: "Pin toolchains and dependencies, then create the package from a clean source revision." },
      { title: "Generate integrity metadata", body: "Record hashes and sign the immutable package using the configured publisher identity." },
      { title: "Review the listing", body: "Explain nodes, capabilities, supported product versions and any migration required." },
      { title: "Publish and verify", body: "Upload the package, install it in a test workspace and compare the resolved integrity." },
    ],
    result: "Users can verify the plugin package and understand its runtime access before installing it.",
    errors: ["A previously published version cannot be replaced with different bytes.", "Breaking node-schema changes require a clear version and workflow migration path."],
    related: ["plugins/manifest", "plugins/permissions", "workflows/revisions-and-publishing"],
  }),

  guide({
    slug: "teams-and-governance/roles",
    section: "Teams and Governance",
    title: "Workspace roles",
    description: "Assign the smallest role that lets each person build, operate or administer safely.",
    concepts: [
      { title: "Workspace role", body: "A collection of permissions applied inside one workspace." },
      { title: "Resource permission", body: "Narrow access to a workflow, connection, runner or environment." },
    ],
    steps: [
      { title: "Separate responsibilities", body: "List who authors workflows, approves changes, manages connections and responds to failures." },
      { title: "Choose the base role", body: "Grant the least powerful workspace role that supports each responsibility." },
      { title: "Add resource access", body: "Limit sensitive connections and production environments to the teams that operate them." },
      { title: "Review regularly", body: "Remove stale membership and confirm administrator access on a fixed cadence." },
    ],
    result: "People can perform their assigned work without inheriting unrelated administrative or secret access.",
    errors: ["Workspace access does not automatically grant a connection or environment.", "Removing a role does not change historical audit attribution."],
    related: ["teams-and-governance/approvals", "teams-and-governance/audit-history", "workflows/permissions"],
  }),
  guide({
    slug: "teams-and-governance/approvals",
    section: "Teams and Governance",
    title: "Require deployment approvals",
    description: "Put a deliberate review between a material workflow change and a protected environment.",
    prerequisites: ["A protected environment", "Distinct author and approver responsibilities"],
    concepts: [
      { title: "Material change", body: "A revision change to logic, capabilities, connections or execution boundary." },
      { title: "Approval record", body: "The reviewer, decision, timestamp and revision preserved with deployment history." },
    ],
    steps: [
      { title: "Define the policy", body: "Choose the environments and change categories that require approval." },
      { title: "Submit a revision", body: "Include the change summary, validation evidence and rollback choice." },
      { title: "Review independently", body: "Compare the immutable revision and its permission delta without editing it." },
      { title: "Approve or return", body: "Record a reason and let deployment proceed only for the exact reviewed revision." },
    ],
    result: "Protected environments run only a revision with a traceable independent decision.",
    errors: ["Editing the draft after submission creates a new revision that needs its own approval.", "An approval does not override a missing connection or runner permission."],
    related: ["teams-and-governance/roles", "teams-and-governance/environments", "workflows/revisions-and-publishing"],
  }),
  guide({
    slug: "teams-and-governance/environments",
    section: "Teams and Governance",
    title: "Separate environments",
    description: "Promote the same workflow logic while binding different runners, connections and data boundaries.",
    concepts: [
      { title: "Environment", body: "A named deployment boundary with its own bindings and policy." },
      { title: "Promotion", body: "Assigning an already reviewed revision to the next environment." },
    ],
    steps: [
      { title: "Create clear stages", body: "Use a small set such as development, test and production with documented purposes." },
      { title: "Bind resources per stage", body: "Map runner pools, folders and connections without embedding environment values in the graph." },
      { title: "Validate promotion", body: "Run representative test data and compare required permissions with the destination." },
      { title: "Promote the revision", body: "Deploy the same immutable revision and observe its first destination execution." },
    ],
    result: "Workflow logic stays identical while access and runtime resources remain environment-specific.",
    errors: ["A destination connection may expose different scopes despite sharing a label.", "Editing workflow logic during promotion creates a different revision and breaks traceability."],
    related: ["teams-and-governance/approvals", "files-and-data/secrets-and-connections", "execution/runner-pools"],
  }),
  guide({
    slug: "teams-and-governance/audit-history",
    section: "Teams and Governance",
    title: "Read audit history",
    description: "Trace administrative and deployment decisions without treating execution logs as an audit log.",
    concepts: [
      { title: "Audit event", body: "An immutable record of who changed workspace control state, what changed and when." },
      { title: "Execution event", body: "Operational detail emitted while a workflow runs; useful, but different in purpose and retention." },
    ],
    steps: [
      { title: "Choose the resource", body: "Filter by workflow, connection, runner, member or environment." },
      { title: "Set the time window", body: "Use the narrow period around the incident or review boundary." },
      { title: "Follow linked revisions", body: "Open the immutable workflow or deployment referenced by the event." },
      { title: "Export deliberately", body: "Preserve event identifiers and applied filters when an authorised review needs an export." },
    ],
    result: "A reviewer can connect a control change to its actor, resource and exact revision.",
    errors: ["Audit history does not reveal protected connection values.", "Local device operating-system events must be reviewed in that system's own logs."],
    related: ["teams-and-governance/roles", "teams-and-governance/approvals", "execution/logs-and-evidence"],
  }),

  guide({
    slug: "developers/authentication",
    section: "Developers",
    title: "API authentication",
    description: "Use short-lived bearer tokens and narrowly scoped service accounts for automation clients.",
    prerequisites: ["Access to the target workspace", "A server-side secret store for unattended clients"],
    concepts: [
      { title: "Access token", body: "A short-lived bearer credential presented to the API over HTTPS." },
      { title: "Service account", body: "A non-human workspace identity with explicit scopes and rotation ownership." },
    ],
    steps: [
      { title: "Choose the identity", body: "Use an interactive user flow for personal tools and a service account for unattended systems." },
      { title: "Grant scopes", body: "Request only the resource actions required by the client." },
      { title: "Store credentials", body: "Keep refresh material or client secrets in a server-side vault, never browser storage or source control." },
      { title: "Rotate and revoke", body: "Record ownership, rotate on schedule and revoke immediately when use ends." },
    ],
    result: "API requests are attributable to a bounded identity whose credential can expire or be revoked.",
    errors: ["HTTP 401 indicates missing, expired or invalid authentication.", "HTTP 403 indicates the authenticated identity lacks the requested workspace scope."],
    related: ["developers/api", "developers/idempotency-and-rate-limits", "teams-and-governance/roles"],
  }),
  guide({
    slug: "developers/typescript-client",
    section: "Developers",
    title: "TypeScript API client",
    description: "Create a typed client, propagate request identity and handle structured API errors.",
    prerequisites: ["Node.js 20 or later", "A Sandbox API token"],
    steps: [
      { title: "Install the package", body: "Pin a compatible client version in the application lockfile.", code: "npm install @sandbox/api-client" },
      { title: "Create one client", body: "Provide the HTTPS base URL and token through server-side configuration.", code: "const sandbox = new SandboxApiClient({\n  baseUrl: process.env.SANDBOX_API_URL,\n  accessToken: process.env.SANDBOX_TOKEN\n});" },
      { title: "Send request identity", body: "Attach a correlation ID and an idempotency key to supported writes." },
      { title: "Handle typed failures", body: "Branch on status and error code while preserving response request IDs in diagnostics." },
    ],
    result: "The integration shares the generated API contract and produces traceable, bounded requests.",
    errors: ["Do not construct the client in browser-delivered code with a service credential.", "Upgrade the client when using fields introduced by a newer API contract."],
    related: ["developers/api/reference", "developers/authentication", "developers/idempotency-and-rate-limits"],
  }),
  guide({
    slug: "developers/idempotency-and-rate-limits",
    section: "Developers",
    title: "Idempotency and rate limits",
    description: "Repeat API writes safely and reduce load when the service asks a client to slow down.",
    concepts: [
      { title: "Idempotency key", body: "A caller-generated identifier that represents one intended write operation." },
      { title: "Rate limit", body: "A bounded request allowance communicated through response status and headers." },
    ],
    steps: [
      { title: "Create the operation key", body: "Generate a stable unique key before the first supported write and persist it with local operation state." },
      { title: "Reuse on uncertainty", body: "Send the same key if a timeout leaves the original response unknown." },
      { title: "Respect throttling", body: "On HTTP 429, use server retry information plus bounded jitter rather than immediate parallel retries." },
      { title: "Cap recovery", body: "Stop after an overall deadline and surface the response request ID for investigation." },
    ],
    result: "Network uncertainty does not create duplicate supported writes, and throttling reduces request pressure.",
    errors: ["A new idempotency key represents a new operation and can repeat the side effect.", "High concurrency can exhaust a shared workspace allowance faster than a single client expects."],
    related: ["developers/api/reference", "execution/retries", "execution/concurrency-and-queues"],
  }),

  guide({
    slug: "troubleshooting/desktop",
    section: "Troubleshooting",
    title: "Desktop app problems",
    description: "Separate an application startup problem from runner, account and workflow failures.",
    steps: [
      { title: "Confirm the release", body: "Record the desktop version and verify it came from the supported signed distribution." },
      { title: "Restart the application", body: "Close the desktop process fully, reopen it and note whether the local workspace loads." },
      { title: "Check platform dependencies", body: "Confirm required runtime components, disk space and operating-system permissions." },
      { title: "Collect bounded diagnostics", body: "Generate the desktop diagnostic bundle and preview its redaction report." },
    ],
    result: "You know whether the failure is application startup, account access or the local runner service.",
    errors: ["Do not delete the application data directory as a first troubleshooting step.", "An unsupported or unsigned build cannot be diagnosed as a trusted release."],
    related: ["getting-started/install", "execution/local-runner", "troubleshooting/diagnostic-bundles"],
  }),
  guide({
    slug: "troubleshooting/browser",
    section: "Troubleshooting",
    title: "Browser runtime problems",
    description: "Diagnose managed Chromium installation, profile locks and site-specific failures.",
    steps: [
      { title: "Check the runtime", body: "Confirm the managed browser version is installed and compatible with the desktop or runner release." },
      { title: "Open the profile", body: "Test whether the selected managed profile starts independently and reaches the target domain." },
      { title: "Reproduce one action", body: "Run the first failing browser node with its original locator and timeout." },
      { title: "Inspect site state", body: "Check authentication, redirects, frames and a bounded failure screenshot." },
    ],
    result: "The issue is narrowed to runtime installation, profile state, page context or a specific browser action.",
    errors: ["A profile already in use cannot safely serve another single-session run.", "Browser automation does not bypass site access controls or human verification."],
    related: ["browser-automation/troubleshooting", "browser-automation/profiles-and-sessions", "browser-automation/screenshots"],
  }),
  guide({
    slug: "troubleshooting/runner",
    section: "Troubleshooting",
    title: "Runner connectivity",
    description: "Find why a local or self-hosted runner is offline, incompatible or unable to reach a target.",
    steps: [
      { title: "Read runner status", body: "Record its last heartbeat, protocol version, labels and current capacity." },
      { title: "Check the service", body: "Confirm the runner process is active under the intended operating-system account." },
      { title: "Verify outbound control traffic", body: "Test DNS, trusted time and HTTPS access to the configured control-plane endpoint." },
      { title: "Test target reachability", body: "From the runner host, verify only the private services and folders required by the workflow." },
    ],
    result: "You can distinguish control-plane connectivity, version compatibility, capacity and target access.",
    errors: ["Clock skew can make signed requests appear invalid.", "A healthy heartbeat does not prove the runner can reach a private workflow target."],
    related: ["execution/self-hosted-runner", "execution/runner-pools", "reference/errors"],
  }),
  guide({
    slug: "troubleshooting/permissions",
    section: "Troubleshooting",
    title: "Permission denied errors",
    description: "Identify which workspace, workflow, runner or operating-system boundary rejected an action.",
    steps: [
      { title: "Read the error owner", body: "Use the code and node context to identify the boundary that returned the denial." },
      { title: "Check the revision", body: "Confirm the running revision declares and has approval for the required capability." },
      { title: "Check the resource binding", body: "Verify the environment supplies the intended connection, folder or runner label." },
      { title: "Check the host last", body: "Confirm the runner service account can access the resource at operating-system level." },
    ],
    result: "The missing grant is repaired at the narrowest boundary without broadening unrelated access.",
    errors: ["Administrator membership does not reveal secret values or bypass workflow capability grants.", "Changing a draft does not update permissions for a deployed revision."],
    related: ["workflows/permissions", "plugins/permissions", "teams-and-governance/roles"],
  }),
  guide({
    slug: "troubleshooting/diagnostic-bundles",
    section: "Troubleshooting",
    title: "Diagnostic bundles",
    description: "Collect versions, structured events and bounded evidence with a visible redaction review.",
    prerequisites: ["An identified execution, runner or desktop incident"],
    concepts: [
      { title: "Bundle scope", body: "The selected incident, time range and components included in the archive." },
      { title: "Redaction report", body: "A preview of protected or sensitive fields removed before export." },
    ],
    steps: [
      { title: "Choose the incident", body: "Start from the failing execution or affected runner to keep collection narrow." },
      { title: "Set the time range", body: "Include enough context to reproduce the transition without exporting unrelated history." },
      { title: "Preview contents", body: "Review file names, event categories, screenshots and every applied redaction." },
      { title: "Share through support", body: "Attach the bundle only to an authenticated support case with the observed and expected behaviour." },
    ],
    result: "Support receives reproducible technical context without raw credentials or an unbounded workspace export.",
    errors: ["A bundle cannot recover log content already removed by retention policy.", "Review screenshots manually because visual content can contain account or customer data."],
    related: ["troubleshooting", "execution/logs-and-evidence", "reference/errors"],
  }),

  guide({
    slug: "reference/limits",
    section: "Reference",
    title: "Product limits",
    description: "Understand the boundaries that keep workflow input, output and execution evidence manageable.",
    notes: ["Exact plan and deployment limits are shown in the product because they can vary by execution boundary."],
    steps: [
      { title: "Check before publishing", body: "Review node count, payload, artifact, duration and concurrency limits in workflow validation." },
      { title: "Bound collections", body: "Process large files and API responses in deliberate batches." },
      { title: "Bound retained evidence", body: "Capture only useful logs, screenshots and output fields." },
      { title: "Plan for the boundary", body: "Confirm runner storage and external-service limits as well as Sandbox limits." },
    ],
    result: "The workflow validates within the limits displayed for its environment and plan.",
    errors: ["Increasing a timeout does not increase the workflow's overall deadline.", "A self-hosted runner does not remove control-plane contract or payload boundaries."],
    related: ["execution/concurrency-and-queues", "execution/logs-and-evidence", "files-and-data/csv"],
  }),
  guide({
    slug: "reference/errors",
    section: "Reference",
    title: "Error model",
    description: "Read stable error codes, retry guidance and request context consistently across surfaces.",
    concepts: [
      { title: "Error code", body: "A stable machine-readable category used by the editor, runner and API." },
      { title: "Request ID", body: "A unique transport identifier that helps trace a specific API or control-plane request." },
      { title: "Retryable", body: "An explicit indication that repeating the operation may succeed without changing its input." },
    ],
    steps: [
      { title: "Start with the code", body: "Use the stable code for handling and the human message for immediate context." },
      { title: "Find the owner", body: "Identify the node, runner, plugin or API request that produced it." },
      { title: "Follow retry guidance", body: "Retry only when the error marks the condition temporary and the operation is safe to repeat." },
      { title: "Preserve context", body: "Keep execution, node, attempt and request identifiers when escalating." },
    ],
    result: "The failure can be handled or reported using stable identity instead of matching message text.",
    errors: ["A validation error is not fixed by retries.", "A redacted detail is intentionally unavailable and should not be reconstructed from logs."],
    related: ["getting-started/understand-executions", "execution/retries", "troubleshooting/diagnostic-bundles"],
  }),
  guide({
    slug: "reference/execution-states",
    section: "Reference",
    title: "Execution states",
    description: "Interpret queued, running, waiting, completed, failed, cancelled and skipped work.",
    concepts: [
      { title: "Execution state", body: "The overall lifecycle state derived from trigger, node and cancellation transitions." },
      { title: "Node state", body: "The lifecycle of one node attempt within the execution graph." },
    ],
    steps: [
      { title: "Queued", body: "The execution is valid but waiting for compatible capacity or an applicable concurrency policy." },
      { title: "Running or waiting", body: "At least one node is active, or the execution is waiting on a declared timer or human boundary." },
      { title: "Completed or failed", body: "The graph reached a successful terminal path, or an unhandled error stopped progress." },
      { title: "Cancelled or skipped", body: "A person or policy stopped remaining work, or a node was unreachable on the selected path." },
    ],
    result: "Operators can distinguish work waiting for capacity from work waiting inside the workflow and from terminal outcomes.",
    errors: ["Skipped is not a failure; inspect the preceding branch or dependency.", "Cancellation can leave already completed external side effects in place."],
    related: ["getting-started/understand-executions", "execution/concurrency-and-queues", "execution/failure-recovery"],
  }),
  guide({
    slug: "reference/data-types",
    section: "Reference",
    title: "Workflow data types",
    description: "Understand the values nodes can validate, map and expose to later steps.",
    concepts: [
      { title: "Scalar", body: "Text, number, boolean, date-time or null represented as one value." },
      { title: "Collection", body: "A bounded ordered list whose entries share an expected item contract." },
      { title: "Object", body: "Named fields validated against a node's input or output schema." },
      { title: "File reference", body: "Metadata and a runner-local handle rather than the complete file embedded in workflow data." },
    ],
    steps: [
      { title: "Keep types explicit", body: "Convert text to number, boolean or date-time before using type-specific comparisons." },
      { title: "Distinguish missing and null", body: "Handle an absent field separately from a field deliberately containing no value." },
      { title: "Project objects", body: "Pass only the fields a downstream node needs." },
      { title: "Bound collections", body: "Validate item count and process large sets in batches." },
    ],
    result: "Mappings fail early when the available value does not match the receiving node's contract.",
    errors: ["Locale-formatted numbers and dates require an explicit parser.", "A file reference is usable only on a runner that can access its bound storage."],
    related: ["workflows/variables-and-data", "files-and-data/json", "files-and-data/files-and-folders"],
  }),
  guide({
    slug: "reference/glossary",
    section: "Reference",
    title: "Glossary",
    description: "A compact map of the terms used throughout Sandbox documentation.",
    concepts: [
      { title: "Workflow", body: "A graph of one trigger and the actions or decisions reachable from it." },
      { title: "Revision", body: "An immutable published snapshot of a workflow." },
      { title: "Deployment", body: "A revision assigned to an environment and execution boundary." },
      { title: "Runner", body: "The trusted local, self-hosted or managed process that executes nodes." },
      { title: "Connection", body: "A protected workspace resource supplying authentication or account context." },
      { title: "Execution", body: "One run of a workflow from trigger input to a terminal state." },
    ],
    steps: [
      { title: "When building", body: "Work in a draft, connect nodes and validate its declared capabilities." },
      { title: "When releasing", body: "Publish an immutable revision, approve it and deploy it to an environment." },
      { title: "When operating", body: "Use execution history, node attempts and runner status to explain outcomes." },
    ],
    result: "Product surfaces and documentation use the same terms for authored logic, released state and runtime activity.",
    errors: ["A workflow is the authored graph; an execution is one run of that graph.", "A runner provides execution capacity; an environment supplies deployment bindings and policy."],
    related: ["getting-started/quick-tour", "workflows/revisions-and-publishing", "reference/execution-states"],
  }),
  guide({
    slug: "nodes/desktop-notification",
    section: "Reference",
    title: "Desktop Notification node",
    description: "Send a local operating-system notification with bounded, non-sensitive content.",
    prerequisites: ["A local runner", "Operating-system notification permission"],
    concepts: [
      { title: "Local action", body: "The notification is created by the desktop runner, not a remote messaging service." },
      { title: "Visible content", body: "Title and message may appear on a locked screen depending on system settings." },
    ],
    steps: [
      { title: "Set title and message", body: "Use short literal text or map non-sensitive workflow output." },
      { title: "Choose urgency", body: "Use the normal system presentation unless a genuinely time-sensitive event requires otherwise." },
      { title: "Test locally", body: "Run the node and confirm both delivery and lock-screen privacy on the target computer." },
    ],
    result: "The local runner posts one clear notification and records the operating-system response.",
    errors: ["System notification settings can block or silence delivery.", "Never map credentials or customer records into visible notification text."],
    related: ["getting-started/first-workflow", "execution/local-runner", "nodes/reference"],
  }),
  guide({
    slug: "nodes/system",
    section: "Reference",
    title: "System nodes",
    description: "Use local files, applications and notifications through explicit runner permissions.",
    concepts: [
      { title: "System capability", body: "A runner-mediated operation on a local operating-system resource." },
      { title: "Approved resource", body: "A named folder or application selected during workflow review." },
    ],
    steps: [
      { title: "Choose the operation", body: "Select the smallest node that performs the required file, application or notification action." },
      { title: "Bind the resource", body: "Use an approved label instead of an arbitrary device path." },
      { title: "Test on the target runner", body: "Verify operating-system access and the node's bounded output before scheduling." },
    ],
    result: "The workflow uses a visible system capability on the intended runner and nowhere else.",
    errors: ["A cloud or different self-hosted runner cannot inherit this computer's resource bindings.", "Operating-system access does not replace a missing workflow grant."],
    related: ["workflows/permissions", "files-and-data/files-and-folders", "nodes/reference"],
  }),
  guide({
    slug: "execution/limits",
    section: "Execution",
    title: "Execution limits",
    description: "Apply runtime deadlines, payload boundaries and artifact caps to keep runs operable.",
    notes: ["The product shows the effective values for the selected environment and plan."],
    steps: [
      { title: "Review validation", body: "Check the effective workflow deadline, node timeout, output and artifact limits." },
      { title: "Split large work", body: "Process large collections in batches with a durable checkpoint between executions." },
      { title: "Keep output focused", body: "Return identifiers and summaries instead of copying full external payloads into history." },
    ],
    result: "The run completes inside its declared time and data boundaries with useful evidence retained.",
    errors: ["A node timeout cannot extend beyond the execution deadline.", "Logs and output can be truncated even when the underlying external action succeeded."],
    related: ["reference/limits", "execution/logs-and-evidence", "execution/concurrency-and-queues"],
  }),
  guide({
    slug: "self-hosting/networking",
    section: "Execution",
    title: "Self-hosted runner networking",
    description: "Allow the runner to reach control services and private workflow targets without exposing inbound administration.",
    prerequisites: ["A supported self-hosted runner host", "Authority to configure outbound network policy"],
    steps: [
      { title: "Allow control traffic", body: "Permit outbound DNS and HTTPS to the configured control-plane endpoints." },
      { title: "Validate trusted time", body: "Keep the host clock synchronised so signed requests can be verified." },
      { title: "Allow workflow targets", body: "Permit only the private hosts and ports required by approved workflows." },
      { title: "Test from the service account", body: "Verify reachability in the same network and identity context used by the runner service." },
    ],
    result: "The runner maintains its control connection and reaches only the targets its workflows need.",
    errors: ["A successful heartbeat does not prove private target reachability.", "TLS interception can fail when the runner cannot trust the substituted certificate chain."],
    related: ["execution/self-hosted-runner", "troubleshooting/runner", "workflows/permissions"],
  }),
  guide({
    slug: "self-hosting/updates",
    section: "Execution",
    title: "Update self-hosted runners",
    description: "Roll out signed runner releases while preserving capacity and protocol compatibility.",
    prerequisites: ["Access to runner hosts", "A verified supported release artifact"],
    steps: [
      { title: "Read compatibility notes", body: "Confirm the target release supports the current control-plane protocol and deployed node set." },
      { title: "Drain one runner", body: "Stop new assignments and wait for active executions to reach a safe terminal state." },
      { title: "Verify and install", body: "Check release integrity, replace the service binary and retain the existing device identity and configuration." },
      { title: "Observe before continuing", body: "Confirm heartbeat, version and a canary workflow before updating more capacity." },
    ],
    result: "Runner capacity returns on the new verified version without interrupting active executions.",
    errors: ["Replacing all pool capacity at once can strand queued work.", "A protocol-incompatible runner remains excluded until it is updated."],
    related: ["execution/self-hosted-runner", "execution/runner-pools", "troubleshooting/runner"],
  }),
  guide({
    slug: "developers/cli",
    section: "Developers",
    title: "Command-line workflows",
    description: "Use command-line tooling for validation and package tasks while keeping API credentials server-side.",
    prerequisites: ["Node.js 20 or later", "A scoped API token when the command accesses a workspace"],
    steps: [
      { title: "Install a pinned tool version", body: "Use the repository or automation lockfile so local and CI commands share behaviour." },
      { title: "Provide configuration", body: "Set the control-plane URL and token through the command environment or a protected CI secret." },
      { title: "Validate before writes", body: "Run local schema and package checks before calling a workspace operation." },
      { title: "Preserve command output", body: "Capture exit status and request identifiers without printing protected environment values." },
    ],
    result: "Local and CI commands are repeatable, versioned and attributable to a narrowly scoped identity.",
    errors: ["Do not pass tokens directly on a command line that may be retained in shell history.", "A non-zero exit should stop dependent deployment steps."],
    related: ["developers/authentication", "developers/typescript-client", "plugins/sdk-setup"],
  }),
  guide({
    slug: "support/diagnostic-bundles",
    section: "Troubleshooting",
    title: "Share diagnostics with support",
    description: "Prepare a narrowly scoped, redacted incident package for an authenticated support case.",
    prerequisites: ["An incident with observed and expected behaviour", "Permission to share the selected workspace diagnostics"],
    steps: [
      { title: "Create the bundle", body: "Select the affected execution or runner and the smallest useful time window." },
      { title: "Review redactions", body: "Inspect the file list, screenshots and protected fields before export." },
      { title: "Describe reproduction", body: "Include the exact action, expected outcome and earliest failing node or request." },
      { title: "Attach securely", body: "Use the authenticated support case rather than email or a public issue." },
    ],
    result: "Support has enough traceable context to investigate without receiving credentials or unrelated workspace data.",
    errors: ["Do not share an unreviewed bundle.", "A bundle's correlation context is most useful when the incident identifiers are included in the case."],
    related: ["troubleshooting/diagnostic-bundles", "troubleshooting", "reference/errors"],
  }),
];
