import * as Tabs from "@radix-ui/react-tabs";
import { Check, Clipboard, Copy, RotateCcw, Square, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { format, formatDistanceStrict } from "date-fns";
import { api } from "../api";
import type { ExecutionRecord, NodeExecution, Workflow } from "../types";
import { Status } from "./Status";

export function ExecutionInspector({run,workflow,onRetry,onClear,compact=false}:{run:ExecutionRecord;workflow?:Workflow;onRetry:()=>void;onClear?:()=>void;compact?:boolean}){const [selected,setSelected]=useState(run.nodeExecutions.find(n=>n.status==="failed")?.nodeId??run.nodeExecutions[0]?.nodeId);useEffect(()=>setSelected(run.nodeExecutions.find(n=>n.status==="failed")?.nodeId??run.nodeExecutions[0]?.nodeId),[run.id]);const nodeRun=run.nodeExecutions.find(n=>n.nodeId===selected);const node=workflow?.nodes.find(n=>n.id===selected);const copy=async(value:unknown)=>navigator.clipboard.writeText(typeof value==="string"?value:JSON.stringify(value,null,2));return <div className={`execution-inspector ${compact?"compact":""}`}><div className="run-summary"><div><Status status={run.status}/><h2>{workflow?.name??"Workflow execution"}</h2><p>{format(new Date(run.startedAt),"dd MMM yyyy · HH:mm:ss")} · {run.durationMs!=null?formatDuration(run.durationMs):"In progress"}</p></div><div className="run-actions">{run.status==="running"&&<button className="button" onClick={()=>api.cancelExecution(run.id)}><Square size={13}/>Cancel</button>}{run.error&&<button className="button" onClick={()=>copy(run.error?.message)}><Copy size={13}/>Copy error</button>}<button className="button" onClick={onRetry}><RotateCcw size={13}/>Retry workflow</button>{onClear&&<button className="icon-button" title="Clear old execution history" onClick={onClear}><Trash2 size={15}/></button>}</div></div>{run.error&&<div className="error-banner"><b>{run.error.message}</b>{run.error.suggestion&&<span>{run.error.suggestion}</span>}</div>}{run.skipReason&&<div className="info-note">{run.skipReason}</div>}<div className="execution-body"><div className="timeline"><div className="timeline-label">Execution timeline</div>{run.nodeExecutions.map((entry,index)=>{const item=workflow?.nodes.find(n=>n.id===entry.nodeId);return <button key={entry.nodeId} className={selected===entry.nodeId?"selected":""} onClick={()=>setSelected(entry.nodeId)}><span className="timeline-rail">{index<run.nodeExecutions.length-1&&<i/>}<Status status={entry.status} label={false}/></span><span><b>{item?.name??entry.nodeId}</b><small>{entry.skipReason??(entry.durationMs!=null?formatDuration(entry.durationMs):entry.status)}</small></span>{entry.retryCount>0&&<em>{entry.retryCount} retries</em>}</button>})}</div>{nodeRun&&<NodeExecutionDetail execution={nodeRun} name={node?.name??nodeRun.nodeId} onCopy={copy}/>}</div></div>}
function NodeExecutionDetail({execution,name,onCopy}:{execution:NodeExecution;name:string;onCopy:(v:unknown)=>void}){return <div className="node-execution-detail"><header><div><h3>{name}</h3><Status status={execution.status}/></div><div><span>Duration <b>{execution.durationMs!=null?formatDuration(execution.durationMs):"—"}</b></span><span>Retries <b>{execution.retryCount}</b></span></div></header>{execution.error&&<div className="error-detail"><b>{execution.error.message}</b>{execution.error.detail&&<p>{execution.error.detail}</p>}{execution.error.suggestion&&<span>{execution.error.suggestion}</span>}</div>}{execution.skipReason&&<div className="skip-detail"><b>Node skipped</b><span>{execution.skipReason}</span>{execution.branchFollowed&&<span>Followed the {execution.branchFollowed} branch.</span>}</div>}<Tabs.Root defaultValue="output"><Tabs.List className="detail-tabs"><Tabs.Trigger value="input">Input</Tabs.Trigger><Tabs.Trigger value="output">Output</Tabs.Trigger><Tabs.Trigger value="logs">Logs <em>{execution.logs.length}</em></Tabs.Trigger></Tabs.List><Tabs.Content value="input"><CodeBlock value={execution.input} onCopy={onCopy}/></Tabs.Content><Tabs.Content value="output"><CodeBlock value={execution.output} onCopy={onCopy}/></Tabs.Content><Tabs.Content value="logs"><div className="logs">{execution.logs.length?execution.logs.map((log,i)=><div key={i}><span>{i+1}</span>{log}</div>):<p>No logs were recorded for this node.</p>}</div></Tabs.Content></Tabs.Root></div>}
function CodeBlock({value,onCopy}:{value:unknown;onCopy:(v:unknown)=>void}){return <div className="code-block"><button onClick={()=>onCopy(value)} title="Copy"><Clipboard size={13}/></button><pre>{JSON.stringify(value,null,2)??"null"}</pre></div>}
const formatDuration=(ms:number)=>ms<1000?`${ms} ms`:formatDistanceStrict(0,ms,{unit:ms<60000?"second":"minute"});
