import { open } from "@tauri-apps/plugin-dialog";
import { AlertTriangle, FolderOpen, ShieldCheck, Trash2 } from "lucide-react";
import { api } from "../api";
import { definitionFor } from "../catalogue";
import type { Workflow, WorkflowNode } from "../types";

export function NodeInspector({workflow,node,onChange,onDelete}:{workflow:Workflow;node:WorkflowNode;onChange:(node:WorkflowNode,workflowPatch?:Partial<Workflow>)=>void;onDelete:()=>void}){const definition=definitionFor(node.type);const Icon=definition.icon;const config=node.configuration;const set=(key:string,value:unknown)=>onChange({...node,configuration:{...config,[key]:value}});const chooseFolder=async(key:string)=>{if(!api.isDesktop)return;const selected=await open({directory:true,multiple:false,title:"Approve a folder for this workflow"});if(typeof selected==="string"){const approved=[...new Set([...workflow.settings.permissions.approvedFolders,selected])];onChange({...node,configuration:{...config,[key]:selected}},{settings:{...workflow.settings,permissions:{...workflow.settings.permissions,approvedFolders:approved}}})}};return <aside className="inspector"><div className="inspector-title"><span className="node-icon"><Icon size={15}/></span><div><b>{node.name}</b><small>{definition.group}</small></div></div><div className="inspector-scroll"><Field label="Name"><input value={node.name} onChange={e=>onChange({...node,name:e.target.value})}/></Field>{node.type==="schedule_trigger"&&<><Field label="Schedule"><select value={String(config.scheduleType??"minutes")} onChange={e=>set("scheduleType",e.target.value)}><option value="minutes">Every X minutes</option><option value="hourly">Hourly</option><option value="daily">Daily</option><option value="cron">Advanced cron</option></select></Field>{config.scheduleType==="minutes"&&<Field label="Every"><div className="input-unit"><input type="number" min="1" value={Number(config.every??15)} onChange={e=>set("every",Number(e.target.value))}/><span>minutes</span></div></Field>}{config.scheduleType==="daily"&&<Field label="Time"><input type="time" value={String(config.time??"09:00")} onChange={e=>set("time",e.target.value)}/></Field>}{config.scheduleType==="cron"&&<Field label="Cron expression" hint="Five or six fields"><input value={String(config.cron??"")} onChange={e=>set("cron",e.target.value)}/></Field>}<Info>Next runs are calculated by the local runner. Quitting Sandbox stops schedules.</Info></>}
{node.type==="file_watch_trigger"&&<><Field label="Folder"><FolderInput value={String(config.folder??"")} onChoose={()=>chooseFolder("folder")}/></Field><Field label="Filename pattern" hint="Optional glob, e.g. *.pdf"><input value={String(config.pattern??"")} onChange={e=>set("pattern",e.target.value)}/></Field><Field label="Events"><div className="checks">{["created","modified","deleted"].map(event=><label key={event}><input type="checkbox" checked={(config.events as string[]??[]).includes(event)} onChange={e=>set("events",e.target.checked?[...new Set([...(config.events as string[]??[]),event])]:(config.events as string[]??[]).filter(v=>v!==event))}/>{event}</label>)}</div></Field></>}
{node.type==="condition"&&<><Field label="Value"><input placeholder="{{nodes.request.output.status}}" value={String(config.left??"")} onChange={e=>set("left",e.target.value)}/></Field><Field label="Operator"><select value={String(config.operator??"equals")} onChange={e=>set("operator",e.target.value)}>{["equals","not_equals","contains","not_contains","greater_than","less_than","exists","not_exists","starts_with","ends_with"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select></Field>{!["exists","not_exists"].includes(String(config.operator))&&<Field label="Compare with"><input value={scalar(config.right)} onChange={e=>set("right",parseScalar(e.target.value))}/></Field>}</>}
{node.type==="set_data"&&<JsonField label="Object" value={config.values??{}} onChange={v=>set("values",v)}/>} {node.type==="delay"&&<><Field label="Duration"><input type="number" min="0" step="0.1" value={Number(config.amount??1)} onChange={e=>set("amount",Number(e.target.value))}/></Field><Field label="Unit"><select value={String(config.unit??"seconds")} onChange={e=>set("unit",e.target.value)}><option value="seconds">Seconds</option><option value="minutes">Minutes</option></select></Field></>}
{node.type==="http_request"&&<><Field label="Method"><select value={String(config.method??"GET")} onChange={e=>set("method",e.target.value)}>{["GET","POST","PUT","PATCH","DELETE"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="URL"><input placeholder="https://api.example.com/status" value={String(config.url??"")} onChange={e=>set("url",e.target.value)}/></Field><JsonField label="Headers" value={config.headers??{}} onChange={v=>set("headers",v)}/><JsonField label="Query parameters" value={config.query??{}} onChange={v=>set("query",v)}/>{!["GET","DELETE"].includes(String(config.method))&&<JsonField label="JSON body" value={config.body??{}} onChange={v=>set("body",v)}/>}<div className="field-grid"><Field label="Timeout (ms)"><input type="number" min="100" max="120000" value={Number(config.timeoutMs??30000)} onChange={e=>set("timeoutMs",Number(e.target.value))}/></Field><Field label="Retries"><input type="number" min="0" max="5" value={Number(config.retryCount??0)} onChange={e=>set("retryCount",Number(e.target.value))}/></Field></div><Info>Authorization and cookie values are redacted from execution data.</Info></>}
{node.type==="desktop_notification"&&<><Field label="Title"><input value={String(config.title??"")} onChange={e=>set("title",e.target.value)}/></Field><Field label="Message"><textarea rows={4} value={String(config.message??"")} onChange={e=>set("message",e.target.value)}/></Field></>}
{node.type==="move_file"&&<><Field label="Source path"><input placeholder="{{trigger.path}}" value={String(config.source??"")} onChange={e=>set("source",e.target.value)}/></Field><Field label="Destination folder"><FolderInput value={String(config.destinationFolder??"")} onChoose={()=>chooseFolder("destinationFolder")}/></Field><Field label="Rename to" hint="Optional"><input value={String(config.renameTo??"")} onChange={e=>set("renameTo",e.target.value)}/></Field><label className="toggle-row"><span><b>Overwrite existing file</b><small>Replace a file with the same name</small></span><input type="checkbox" checked={Boolean(config.overwrite)} onChange={e=>set("overwrite",e.target.checked)}/></label></>}
{node.type==="run_command"&&<><div className="risk-callout"><AlertTriangle size={16}/><div><b>High-risk capability</b><p>Automatic runs require an explicit permission review. The executable and each argument are passed separately.</p></div></div><Field label="Executable"><input placeholder="C:\Tools\processor.exe" value={String(config.executable??"")} onChange={e=>set("executable",e.target.value)}/></Field><Field label="Arguments" hint="One argument per line"><textarea rows={4} value={(config.arguments as string[]??[]).join("\n")} onChange={e=>set("arguments",e.target.value.split("\n"))}/></Field><Field label="Working directory"><FolderInput value={String(config.workingDirectory??"")} onChoose={()=>chooseFolder("workingDirectory")}/></Field></>}
<label className="toggle-row"><span><b>Disable node</b><small>Keep it in the workflow without running it</small></span><input type="checkbox" checked={node.disabled} onChange={e=>onChange({...node,disabled:e.target.checked})}/></label></div><div className="inspector-footer"><button className="button danger-text" onClick={onDelete}><Trash2 size={14}/>Delete node</button><button className="button"><ShieldCheck size={14}/>Permissions</button></div></aside>}
function Field({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}){return <label className="field"><span>{label}{hint&&<small>{hint}</small>}</span>{children}</label>}
function FolderInput({value,onChoose}:{value:string;onChoose:()=>void}){return <div className="folder-input"><input value={value} readOnly placeholder="Choose an approved folder"/><button type="button" onClick={onChoose} disabled={!api.isDesktop}><FolderOpen size={15}/></button></div>}
function Info({children}:{children:React.ReactNode}){return <div className="info-note">{children}</div>}
function scalar(value:unknown){return typeof value==="string"?value:JSON.stringify(value??"")}
function parseScalar(value:string){if(value==="true")return true;if(value==="false")return false;if(value==="null")return null;if(value.trim()!==""&&!Number.isNaN(Number(value)))return Number(value);return value}
function JsonField({label,value,onChange}:{label:string;value:unknown;onChange:(v:unknown)=>void}){let text:string;try{text=JSON.stringify(value,null,2)}catch{text="{}"}return <Field label={label} hint="JSON or safe {{reference}} values"><textarea className="code-input" rows={5} defaultValue={text} onBlur={e=>{try{onChange(JSON.parse(e.target.value));e.target.setCustomValidity("")}catch{e.target.setCustomValidity("Enter valid JSON");e.target.reportValidity()}}}/></Field>}
