import { listen } from "@tauri-apps/api/event";
import { Background, BackgroundVariant, Controls, MiniMap, ReactFlow, useNodesState, type Connection, type Edge, type Node, type NodeChange, type ReactFlowInstance } from "@xyflow/react";
import { AlertTriangle, ArrowLeft, ChevronDown, ChevronUp, Command, History, LayoutGrid, Play, Save, ShieldCheck, TestTube2 } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { api } from "../api";
import { createNode, isTrigger } from "../catalogue";
import { useAppStore } from "../store";
import type { ExecutionRecord, NodeStatus, NodeType, PermissionSummary, ValidationIssue, Workflow } from "../types";
import { CommandPalette } from "./CommandPalette";
import { ExecutionInspector } from "./ExecutionInspector";
import { NodeInspector } from "./NodeInspector";
import { WorkflowNodeCard, type WorkflowNodeData } from "./WorkflowNodeCard";

const nodeTypes={workflow:WorkflowNodeCard};
export function WorkflowEditor(){const {activeWorkflow,setView,saveWorkflow}=useAppStore();const [workflow,setWorkflow]=useState(()=>structuredClone(activeWorkflow!));const [baseline,setBaseline]=useState(()=>JSON.stringify(activeWorkflow));const [selectedNodeId,setSelectedNodeId]=useState<string>();const [picker,setPicker]=useState<{open:boolean;sourceId?:string;position:{x:number;y:number}}>({open:false,position:{x:360,y:220}});const [instance,setInstance]=useState<ReactFlowInstance<Node<WorkflowNodeData>,Edge>>();const [issues,setIssues]=useState<ValidationIssue[]>([]);const [runningNode,setRunningNode]=useState<string>();const [run,setRun]=useState<ExecutionRecord>();const [bottomOpen,setBottomOpen]=useState(false);const [saving,setSaving]=useState(false);const [running,setRunning]=useState(false);const [permissionOpen,setPermissionOpen]=useState(false);const past=useRef<Workflow[]>([]);const future=useRef<Workflow[]>([]);const dirty=JSON.stringify(workflow)!==baseline;const selectedNode=workflow.nodes.find(n=>n.id===selectedNodeId);
  const commit=useCallback((next:Workflow)=>{past.current.push(structuredClone(workflow));if(past.current.length>50)past.current.shift();future.current=[];setWorkflow(next)},[workflow]);
  const patchWorkflow=useCallback((patch:Partial<Workflow>)=>commit({...workflow,...patch}),[workflow,commit]);
  const goBack=()=>{if(!dirty||confirm("Leave without saving your workflow changes?"))setView("workflows")};
  useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",before);return()=>window.removeEventListener("beforeunload",before)},[dirty]);
  useEffect(()=>{(window as Window&{__sandboxUnsaved?:boolean}).__sandboxUnsaved=dirty;return()=>{(window as Window&{__sandboxUnsaved?:boolean}).__sandboxUnsaved=false}},[dirty]);
  useEffect(()=>{const openPicker=()=>setPicker({open:true,position:{x:360,y:220}});window.addEventListener("sandbox:open-node-picker",openPicker);return()=>window.removeEventListener("sandbox:open-node-picker",openPicker)},[]);
  useEffect(()=>{if(!api.isDesktop)return;let stop:undefined|(()=>void);listen<{type:string;node_id?:string;record?:ExecutionRecord}>("runner-event",event=>{if(event.payload.type==="node_started")setRunningNode(event.payload.node_id);if(event.payload.type==="execution_updated"&&event.payload.record?.workflowId===workflow.id){setRun(event.payload.record);setBottomOpen(true);if(event.payload.record.status!=="running")setRunningNode(undefined)}}).then(fn=>stop=fn);return()=>stop?.()},[workflow.id]);
  const doSave=useCallback(async()=>{setSaving(true);try{const saved=await saveWorkflow(workflow);setWorkflow(saved);setBaseline(JSON.stringify(saved))}finally{setSaving(false)}},[workflow,saveWorkflow]);
  const test=useCallback(async()=>{const result=await api.validateWorkflow(workflow);setIssues(result);if(result.length)setBottomOpen(true);return result},[workflow]);
  const doRun=useCallback(async()=>{await doSave();const result=await test();if(result.length)return;setRunning(true);setBottomOpen(true);try{const execution=await api.runWorkflow(workflow.id);setRun(execution)}catch(error){setIssues([{code:"runner_error",message:String(error)}])}finally{setRunning(false);setRunningNode(undefined)}},[doSave,test,workflow.id]);
  const removeNode=useCallback((id:string)=>{const node=workflow.nodes.find(n=>n.id===id);if(!node)return;const configured=Object.keys(node.configuration).length>0&&Object.values(node.configuration).some(v=>v!==""&&v!=null);if(configured&&!confirm(`Delete configured node “${node.name}”?`))return;commit({...workflow,nodes:workflow.nodes.filter(n=>n.id!==id),edges:workflow.edges.filter(e=>e.sourceNodeId!==id&&e.targetNodeId!==id)});setSelectedNodeId(undefined)},[workflow,commit]);
  const duplicate=useCallback((id:string)=>{const original=workflow.nodes.find(n=>n.id===id);if(!original||isTrigger(original.type))return;const copy={...structuredClone(original),id:`${original.type}_${crypto.randomUUID().slice(0,8)}`,name:`${original.name} copy`,position:{x:original.position.x+32,y:original.position.y+96}};commit({...workflow,nodes:[...workflow.nodes,copy]});setSelectedNodeId(copy.id)},[workflow,commit]);
  const undo=useCallback(()=>{const previous=past.current.pop();if(previous){future.current.push(structuredClone(workflow));setWorkflow(previous)}},[workflow]);const redo=useCallback(()=>{const next=future.current.pop();if(next){past.current.push(structuredClone(workflow));setWorkflow(next)}},[workflow]);
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(target.closest("input,textarea,select,[contenteditable=true]")){if(e.key==="Escape")(target as HTMLElement).blur();return}const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==="s"){e.preventDefault();doSave()}else if(mod&&e.key==="Enter"){e.preventDefault();doRun()}else if(mod&&e.key.toLowerCase()==="d"&&selectedNodeId){e.preventDefault();duplicate(selectedNodeId)}else if(mod&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo()}else if((e.key==="Delete"||e.key==="Backspace")&&selectedNodeId){e.preventDefault();removeNode(selectedNodeId)}else if(e.key==="Escape"){setSelectedNodeId(undefined);setPicker(p=>({...p,open:false}))}else if(mod&&e.key.toLowerCase()==="k"){e.preventDefault();setPicker({open:true,position:{x:360,y:220}})}else if(e.key.toLowerCase()==="a"&&!mod){setPicker({open:true,position:{x:360,y:220}})}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[doSave,doRun,duplicate,redo,removeNode,selectedNodeId,undo]);
  const addNode=(type:NodeType)=>{if(isTrigger(type)&&workflow.nodes.some(n=>isTrigger(n.type))){setIssues([{code:"trigger_count",message:"A workflow can contain only one trigger. Replace the existing trigger instead."}]);setBottomOpen(true);return}const node=createNode(type,picker.position);let edges=workflow.edges;if(picker.sourceId)edges=[...edges,{id:`edge_${crypto.randomUUID().slice(0,8)}`,sourceNodeId:picker.sourceId,sourceHandle:workflow.nodes.find(n=>n.id===picker.sourceId)?.type==="condition"?"true":"output",targetNodeId:node.id,targetHandle:"input"}];commit({...workflow,nodes:[...workflow.nodes,node],edges});setSelectedNodeId(node.id)};
  const tidy=()=>{const levels=new Map<string,number>([[workflow.triggerNodeId,0]]);for(let i=0;i<workflow.nodes.length;i++)for(const edge of workflow.edges){const source=levels.get(edge.sourceNodeId);if(source!=null)levels.set(edge.targetNodeId,Math.max(levels.get(edge.targetNodeId)??0,source+1))}const counts=new Map<number,number>();patchWorkflow({nodes:workflow.nodes.map(n=>{const level=levels.get(n.id)??0;const count=counts.get(level)??0;counts.set(level,count+1);return{...n,position:{x:60+level*280,y:160+count*180}}})})};
  const nodeWarnings=new Map(issues.filter(i=>i.nodeId).map(i=>[i.nodeId!,i.message]));
  const flowNodes:Node<WorkflowNodeData>[] = workflow.nodes.map(node=>({
    id:node.id,
    type:"workflow",
    position:node.position,
    selected:node.id===selectedNodeId,
    data:{
      node,
      status:(runningNode===node.id?"running":run?.nodeExecutions.find(e=>e.nodeId===node.id)?.status??"idle") as NodeStatus,
      warning:nodeWarnings.get(node.id),
      onAdd:(sourceId:string)=>{
        const source=workflow.nodes.find(n=>n.id===sourceId)!;
        setPicker({open:true,sourceId,position:{x:source.position.x+280,y:source.position.y}});
      },
    },
  }));
  const [displayNodes,setDisplayNodes,onDisplayNodesChange]=useNodesState<Node<WorkflowNodeData>>(flowNodes);
  useEffect(()=>{setDisplayNodes(current=>flowNodes.map(node=>{const existing=current.find(item=>item.id===node.id);return existing?{...existing,...node}:node}))},[workflow.nodes,selectedNodeId,runningNode,run,issues,setDisplayNodes]);
  const flowEdges:Edge[]=workflow.edges.map(edge=>({id:edge.id,source:edge.sourceNodeId,target:edge.targetNodeId,sourceHandle:edge.sourceHandle,targetHandle:edge.targetHandle,type:"smoothstep",animated:Boolean(runningNode&&edge.sourceNodeId===runningNode),className:run?.nodeExecutions.find(n=>n.nodeId===edge.sourceNodeId)?.status==="successful"?"edge-success":""}));
  const onNodesChange=(changes:NodeChange<Node<WorkflowNodeData>>[])=>{onDisplayNodesChange(changes);let changed=false;const nodes=workflow.nodes.map(node=>{const change=changes.find(c=>"id" in c&&c.id===node.id);if(change?.type==="position"&&change.position){changed=true;return{...node,position:change.position}}if(change?.type==="select"&&change.selected)setSelectedNodeId(node.id);return node});if(changed)setWorkflow({...workflow,nodes})};
  const onConnect=(connection:Connection)=>{if(!connection.source||!connection.target||connection.source===connection.target)return;const target=workflow.nodes.find(n=>n.id===connection.target);if(target&&isTrigger(target.type))return;const exists=workflow.edges.some(e=>e.sourceNodeId===connection.source&&e.targetNodeId===connection.target&&e.sourceHandle===(connection.sourceHandle??"output"));if(exists)return;commit({...workflow,edges:[...workflow.edges,{id:`edge_${crypto.randomUUID().slice(0,8)}`,sourceNodeId:connection.source,sourceHandle:connection.sourceHandle??"output",targetNodeId:connection.target,targetHandle:connection.targetHandle??"input"}]})};
  return <main className="editor">
    <header className="editor-topbar">
      <button className="icon-button" onClick={goBack} title="Back to workflows"><ArrowLeft size={16}/></button>
      <input className="workflow-title-input" value={workflow.name} onChange={e=>setWorkflow({...workflow,name:e.target.value})}/>
      {dirty&&<span className="unsaved-dot" title="Unsaved changes"/>}
      <label className="enabled-toggle"><input type="checkbox" checked={workflow.enabled} onChange={e=>setWorkflow({...workflow,enabled:e.target.checked})}/><span/>{workflow.enabled?"Enabled":"Disabled"}</label>
      <div className="topbar-spacer"/>
      <button className="button" onClick={tidy}><LayoutGrid size={14}/>Tidy</button>
      <button className="button" onClick={()=>setPermissionOpen(true)}><ShieldCheck size={14}/>Permissions</button>
      <button className="button" onClick={test}><TestTube2 size={14}/>Test</button>
      <button className="button" disabled={!dirty||saving} onClick={doSave}><Save size={14}/>{saving?"Saving…":"Save"}</button>
      <button className="button primary" disabled={running} onClick={doRun}><Play size={14} fill="currentColor"/>{running?"Running…":"Run"}</button>
    </header>
    <div className={`editor-body ${selectedNode?"with-inspector":""}`}>
      <div className="canvas-wrap" onDoubleClick={event=>{if(!(event.target as HTMLElement).classList.contains("react-flow__pane"))return;const position=instance?.screenToFlowPosition({x:event.clientX,y:event.clientY})??{x:360,y:220};setPicker({open:true,position});}}>
        <ReactFlow<Node<WorkflowNodeData>,Edge> nodes={displayNodes} edges={flowEdges} nodeTypes={nodeTypes} onInit={setInstance} onNodesChange={onNodesChange} onNodeClick={(_,node)=>setSelectedNodeId(node.id)} onPaneClick={()=>setSelectedNodeId(undefined)} onConnect={onConnect} isValidConnection={connection=>{const target=workflow.nodes.find(n=>n.id===connection.target);return connection.source!==connection.target&&!Boolean(target&&isTrigger(target.type));}} snapToGrid snapGrid={[20,20]} minZoom={0.45} maxZoom={1.8} defaultViewport={{x:80,y:80,zoom:.9}} deleteKeyCode={null} multiSelectionKeyCode="Shift" fitView>
          <Background variant={BackgroundVariant.Dots} gap={20} size={1} color="#292a2e"/><Controls showInteractive={false}/><MiniMap pannable zoomable nodeColor="#24252a" maskColor="rgba(8,8,9,.72)"/>
        </ReactFlow>
        <div className="canvas-hint"><Command size={13}/>Double-click canvas or press A to add a node</div>
      </div>
      {selectedNode&&<NodeInspector workflow={workflow} node={selectedNode} onChange={(node,workflowPatch)=>{const next={...workflow,...workflowPatch,nodes:workflow.nodes.map(n=>n.id===node.id?node:n)};commit(next);}} onDelete={()=>removeNode(selectedNode.id)}/>} 
    </div>
    <section className={`execution-drawer ${bottomOpen?"open":""}`}>
      <button className="drawer-handle" onClick={()=>setBottomOpen(v=>!v)}><History size={14}/><span>Execution & data</span>{run&&<span className={`drawer-status status-${run.status}`}>{run.status}</span>}{issues.length>0&&<span className="warning-count"><AlertTriangle size={13}/>{issues.length} issue{issues.length===1?"":"s"}</span>}<span className="topbar-spacer"/>{bottomOpen?<ChevronDown size={15}/>:<ChevronUp size={15}/>}</button>
      {bottomOpen&&<div className="drawer-content">{issues.length>0?<div className="validation-list"><h3>Workflow needs attention</h3>{issues.map((issue,i)=><button key={i} onClick={()=>issue.nodeId&&setSelectedNodeId(issue.nodeId)}><AlertTriangle size={14}/><span><b>{issue.message}</b><small>{issue.nodeId?workflow.nodes.find(n=>n.id===issue.nodeId)?.name:"Workflow"}</small></span></button>)}</div>:run?<ExecutionInspector compact run={run} workflow={workflow} onRetry={doRun}/>:<div className="drawer-empty"><TestTube2 size={18}/><b>No execution selected</b><span>Test the workflow for validation or run it to inspect live data.</span></div>}</div>}
    </section>
    <CommandPalette open={picker.open} onClose={()=>setPicker(p=>({...p,open:false}))} onCreate={()=>{}} onAdd={addNode}/>
    {permissionOpen&&<PermissionReview workflow={workflow} onClose={()=>setPermissionOpen(false)} onApply={permissions=>{setWorkflow({...workflow,settings:{...workflow.settings,permissions}});setPermissionOpen(false);}}/>}
  </main>;
}

function PermissionReview({workflow,onClose,onApply}:{workflow:Workflow;onClose:()=>void;onApply:(p:PermissionSummary)=>void}){const [permissions,setPermissions]=useState(workflow.settings.permissions);const domains=workflow.nodes.filter(n=>n.type==="http_request").map(n=>{try{return new URL(String(n.configuration.url)).hostname}catch{return""}}).filter(Boolean);const commandNodes=workflow.nodes.filter(n=>n.type==="run_command");return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="permission-modal"><header><span className="permission-icon"><ShieldCheck size={18}/></span><div><h2>Workflow permissions</h2><p>Review what this workflow may access when it runs locally.</p></div></header><section><label>Approved network domains</label>{domains.length?domains.map(domain=><div className="permission-row" key={domain}><span>↗</span><b>{domain}</b><em>Required by HTTP Request</em></div>):<div className="permission-empty">No network access requested.</div>}<label>Approved folders</label>{permissions.approvedFolders.length?permissions.approvedFolders.map(folder=><div className="permission-row" key={folder}><span>⌁</span><b>{folder}</b></div>):<div className="permission-empty">No folder access approved.</div>}{commandNodes.length>0&&<><label>Command execution</label>{commandNodes.map(node=><div className="command-review" key={node.id}><AlertTriangle size={15}/><div><b>{String(node.configuration.executable||"Executable not configured")}</b><code>{((node.configuration.arguments as string[])??[]).join(" ")||"No arguments"}</code></div></div>)}<label className="toggle-row"><span><b>Permit command execution</b><small>Changing a command revokes this approval.</small></span><input type="checkbox" checked={permissions.commandExecutionPermitted} onChange={e=>setPermissions({...permissions,commandExecutionPermitted:e.target.checked,approvalRevision:e.target.checked?crypto.randomUUID():null})}/></label></>}<label className="toggle-row"><span><b>Permit background execution</b><small>Required for schedules and file watches while the window is in the tray.</small></span><input type="checkbox" checked={permissions.backgroundExecutionPermitted} onChange={e=>setPermissions({...permissions,backgroundExecutionPermitted:e.target.checked})}/></label><div className="quit-note">Local schedules stop when Sandbox is fully quit.</div></section><footer><button className="button" onClick={onClose}>Cancel</button><button className="button primary" onClick={()=>onApply({...permissions,approvedNetworkDomains:[...new Set([...permissions.approvedNetworkDomains,...domains])]})}>Apply permissions</button></footer></div></div>}
