import { invoke } from "@tauri-apps/api/core";
import type { AccountStatus, BrowserEngineStatus, BrowserProfile, BrowserProfileSettings, ConnectionMetadata, ExecutionRecord, PendingApproval, PermissionSummary, RecordedStep, RunnerStatus, StructuredLocator, ValidationIssue, Workflow, WorkflowSummary } from "./types";
import { previewApi } from "./previewApi";
const tauri=typeof window!=="undefined"&&"__TAURI_INTERNALS__" in window;
export const api={
  listWorkflows:()=>tauri?invoke<WorkflowSummary[]>("list_workflows"):previewApi.listWorkflows(),
  getWorkflow:(id:string)=>tauri?invoke<Workflow|undefined>("get_workflow",{id}):previewApi.getWorkflow(id),
  saveWorkflow:(workflow:Workflow)=>tauri?invoke<Workflow>("save_workflow",{workflow}):previewApi.saveWorkflow(workflow),
  createWorkflow:(templateKey?:string,name?:string)=>tauri?invoke<Workflow>("create_workflow",{templateKey,name}):previewApi.createWorkflow(templateKey,name),
  exportWorkflow:(id:string)=>tauri?invoke<string|undefined>("export_workflow",{id}):Promise.reject(new Error("Workflow export uses a native file picker in the desktop application.")),
  importWorkflow:()=>tauri?invoke<Workflow|undefined>("import_workflow"):Promise.reject(new Error("Workflow import uses a native file picker in the desktop application.")),
  deleteWorkflow:(id:string)=>tauri?invoke<void>("delete_workflow",{id}):previewApi.deleteWorkflow(id),
  validateWorkflow:(workflow:Workflow)=>tauri?invoke<ValidationIssue[]>("validate_workflow",{workflow}):previewApi.validateWorkflow(workflow),
  runWorkflow:(id:string)=>tauri?invoke<ExecutionRecord>("run_workflow",{id,trigger:{type:"manual"}}):previewApi.runWorkflow(id),
  retryFailedNode:(executionId:string,nodeId:string)=>tauri?invoke<ExecutionRecord>("retry_failed_node",{executionId,nodeId}):previewApi.retryFailedNode(executionId,nodeId),
  retryBrowserExecutionHeaded:(executionId:string)=>tauri?invoke<ExecutionRecord>("retry_browser_execution_headed",{executionId}):Promise.reject(new Error("Headed browser retries require the desktop application.")),
  openExecutionArtifact:(path:string)=>tauri?invoke<void>("open_execution_artifact",{path}):Promise.reject(new Error("Execution artifacts are available only in the desktop application.")),
  cancelExecution:(executionId:string)=>tauri?invoke<void>("cancel_execution",{executionId}):previewApi.cancelExecution(),
  listExecutions:(workflowId?:string,limit=100)=>tauri?invoke<ExecutionRecord[]>("list_executions",{workflowId,limit}):previewApi.listExecutions(workflowId),
  getExecution:(id:string)=>tauri?invoke<ExecutionRecord|undefined>("get_execution",{id}):previewApi.getExecution(id),
  clearExecutionHistory:(keep=0)=>tauri?invoke<number>("clear_execution_history",{keep}):previewApi.clearExecutionHistory(),
  approvePermissions:(id:string,permissions:PermissionSummary)=>invoke<Workflow>("approve_permissions",{id,permissions}),
  runnerStatus:()=>tauri?invoke<RunnerStatus>("runner_status"):Promise.resolve({paused:false,activeWorkflowIds:[],localSchedulesStopOnQuit:true}),
  browserEngineStatus:()=>tauri?invoke<BrowserEngineStatus>("browser_engine_status"):Promise.resolve({available:true,protocolVersion:1,sidecarVersion:"0.2.0",browserName:"chromium",browserVersion:"151.0.7922.34"}),
  restartBrowserEngine:()=>invoke<BrowserEngineStatus>("restart_browser_engine"),
  listBrowserProfiles:()=>tauri?invoke<BrowserProfile[]>("list_browser_profiles"):previewApi.listBrowserProfiles(),
  createBrowserProfile:(name:string,persistent=true,settings?:BrowserProfileSettings)=>tauri?invoke<BrowserProfile>("create_browser_profile",{name,persistent,settings}):previewApi.createBrowserProfile(name,persistent,settings),
  updateBrowserProfile:(id:string,name:string,persistent:boolean,settings:BrowserProfileSettings)=>tauri?invoke<BrowserProfile>("update_browser_profile",{id,name,persistent,settings}):previewApi.updateBrowserProfile(id,name,persistent,settings),
  duplicateBrowserProfile:(id:string)=>tauri?invoke<BrowserProfile>("duplicate_browser_profile",{id}):previewApi.duplicateBrowserProfile(id),
  clearBrowserProfileData:(id:string)=>invoke<void>("clear_browser_profile_data",{id}),
  deleteBrowserProfile:(id:string)=>tauri?invoke<void>("delete_browser_profile",{id}):previewApi.deleteBrowserProfile(id),
  openBrowserProfile:(id:string)=>invoke<Record<string,unknown>>("open_browser_profile",{id}),
  startBrowserRecording:(profileId:string,initialUrl?:string)=>invoke<{browserSession:{sessionId:string}}>("start_browser_recording",{profileId,initialUrl}),
  getBrowserRecording:(sessionId:string)=>invoke<{steps:RecordedStep[]}>("get_browser_recording",{sessionId}),
  stopBrowserRecording:(sessionId:string)=>invoke<{steps:RecordedStep[]}>("stop_browser_recording",{sessionId}),
  testBrowserLocator:(sessionId:string,locator:StructuredLocator)=>invoke<Record<string,unknown>>("test_browser_locator",{sessionId,locator}),
  listConnections:()=>tauri?invoke<ConnectionMetadata[]>("list_connections"):previewApi.listConnections(),
  createConnection:(provider:string,displayName:string,secret:Record<string,unknown>,accountIdentifier?:string,scopes:string[]=[],metadata:Record<string,unknown>={})=>tauri?invoke<ConnectionMetadata>("create_connection",{provider,displayName,accountIdentifier,scopes,metadata,secret}):Promise.reject(new Error("Connections use the operating-system credential store and are available only in the desktop application.")),
  renameConnection:(id:string,displayName:string)=>invoke<ConnectionMetadata>("rename_connection",{id,displayName}),
  reconnectConnection:(id:string,secret:Record<string,unknown>)=>invoke<ConnectionMetadata>("reconnect_connection",{id,secret}),
  testConnection:(id:string)=>invoke<{healthy:boolean;message:string}>("test_connection",{id}),
  revokeConnection:(id:string)=>invoke<ConnectionMetadata>("revoke_connection",{id}),
  deleteConnection:(id:string)=>invoke<void>("delete_connection",{id}),
  workflowsUsingConnection:(id:string)=>invoke<string[]>("workflows_using_connection",{id}),
  startGmailOAuth:()=>tauri?invoke<{authorizationUrl:string;expiresAt:string}>("start_gmail_oauth"):Promise.reject(new Error("Gmail OAuth requires the desktop application and SANDBOX_GMAIL_CLIENT_ID.")),
  accountStatus:()=>tauri?invoke<AccountStatus>("account_status"):Promise.resolve({configured:false,signedIn:false,localWorkflowsAvailable:true,configurationError:"Accounts are available in the desktop application."}),
  startAccountAuth:(createAccount=false)=>tauri?invoke<{authorizationUrl:string;expiresAt:string}>("start_account_auth",{createAccount}):Promise.reject(new Error("Account authorization opens the system browser from the desktop application.")),
  signOutAccount:()=>tauri?invoke<void>("sign_out_account"):Promise.resolve(),
  listPendingApprovals:()=>tauri?invoke<PendingApproval[]>("list_pending_approvals"):Promise.resolve([]),
  resolvePendingApproval:(id:string,approved:boolean)=>invoke<void>("resolve_pending_approval",{id,approved}),
  isDesktop:tauri,
};
