import type { ExecutionRecord, NodeExecution, ValidationIssue, Workflow, WorkflowSummary } from "./types";

const KEY="sandbox-preview-workflows"; const RUNS="sandbox-preview-runs";
const now=()=>new Date().toISOString();
const blank=(template="blank"):Workflow=>{
  const id=crypto.randomUUID(); const createdAt=now();
  const base={id,schemaVersion:1,description:"",enabled:false,settings:{defaultNodeTimeoutMs:30000,maxConcurrentNodes:4,permissions:{approvedFolders:[],approvedNetworkDomains:[],commandExecutionPermitted:false,backgroundExecutionPermitted:false}},createdAt,updatedAt:createdAt};
  if(template==="website-health")return{...base,name:"Website Health Monitor",triggerNodeId:"manual_trigger",settings:{...base.settings,permissions:{...base.settings.permissions,approvedNetworkDomains:["example.com"]}},nodes:[
    {id:"manual_trigger",type:"manual_trigger",version:1,name:"Manual Trigger",position:{x:60,y:220},configuration:{},disabled:false},
    {id:"http_request",type:"http_request",version:1,name:"HTTP Request",position:{x:340,y:220},configuration:{method:"GET",url:"https://example.com",timeoutMs:30000,retryCount:1,headers:{},query:{}},disabled:false},
    {id:"condition",type:"condition",version:1,name:"Condition",position:{x:620,y:220},configuration:{left:"{{nodes.http_request.output.status}}",operator:"equals",right:200},disabled:false},
    {id:"notification_success",type:"desktop_notification",version:1,name:"Desktop Notification",position:{x:920,y:150},configuration:{title:"Website is healthy",message:"example.com returned 200"},disabled:false},
    {id:"notification_failed",type:"desktop_notification",version:1,name:"Desktop Notification",position:{x:920,y:330},configuration:{title:"Website needs attention",message:"Check the latest response"},disabled:false}],edges:[
      {id:"e1",sourceNodeId:"manual_trigger",sourceHandle:"output",targetNodeId:"http_request",targetHandle:"input"},{id:"e2",sourceNodeId:"http_request",sourceHandle:"output",targetNodeId:"condition",targetHandle:"input"},{id:"e3",sourceNodeId:"condition",sourceHandle:"true",targetNodeId:"notification_success",targetHandle:"input"},{id:"e4",sourceNodeId:"condition",sourceHandle:"false",targetNodeId:"notification_failed",targetHandle:"input"}]};
  if(template==="downloads-organiser")return{...base,name:"Downloads Folder Organiser",triggerNodeId:"file_watch",nodes:[{id:"file_watch",type:"file_watch_trigger",version:1,name:"File Watch Trigger",position:{x:60,y:220},configuration:{folder:"",events:["created"],pattern:"*.pdf"},disabled:false},{id:"condition",type:"condition",version:1,name:"Condition",position:{x:340,y:220},configuration:{left:"{{trigger.extension}}",operator:"equals",right:"pdf"},disabled:false},{id:"move_file",type:"move_file",version:1,name:"Move File",position:{x:650,y:150},configuration:{source:"{{trigger.path}}",destinationFolder:"",renameTo:"",overwrite:false},disabled:false}],edges:[{id:"e1",sourceNodeId:"file_watch",sourceHandle:"output",targetNodeId:"condition",targetHandle:"input"},{id:"e2",sourceNodeId:"condition",sourceHandle:"true",targetNodeId:"move_file",targetHandle:"input"}]};
  return{...base,name:"Untitled workflow",triggerNodeId:"manual_trigger",nodes:[{id:"manual_trigger",type:"manual_trigger",version:1,name:"Manual Trigger",position:{x:80,y:220},configuration:{},disabled:false}],edges:[]};
};
const workflows=()=>JSON.parse(localStorage.getItem(KEY)??"[]") as Workflow[]; const saveAll=(v:Workflow[])=>localStorage.setItem(KEY,JSON.stringify(v));
const runs=()=>JSON.parse(localStorage.getItem(RUNS)??"[]") as ExecutionRecord[]; const saveRuns=(v:ExecutionRecord[])=>localStorage.setItem(RUNS,JSON.stringify(v));
export const previewApi={
  async listWorkflows():Promise<WorkflowSummary[]>{return workflows().map(workflow=>({workflow,lastExecution:runs().find(r=>r.workflowId===workflow.id)}));},
  async getWorkflow(id:string){return workflows().find(w=>w.id===id)},
  async saveWorkflow(workflow:Workflow){workflow.updatedAt=now();const all=workflows();const i=all.findIndex(w=>w.id===workflow.id);if(i<0)all.unshift(workflow);else all[i]=workflow;saveAll(all);return workflow},
  async createWorkflow(templateKey?:string,name?:string){const w=blank(templateKey);if(name)w.name=name;saveAll([w,...workflows()]);return w},
  async deleteWorkflow(id:string){saveAll(workflows().filter(w=>w.id!==id))},
  async validateWorkflow(workflow:Workflow):Promise<ValidationIssue[]>{const issues:ValidationIssue[]=[];const triggers=workflow.nodes.filter(n=>n.type.endsWith("trigger"));if(triggers.length!==1)issues.push({code:"trigger_count",message:`Workflow requires exactly one trigger; found ${triggers.length}.`});workflow.nodes.forEach(n=>{if(n.type==="http_request"&&!n.configuration.url)issues.push({code:"incomplete_node",message:"HTTP Request requires a URL.",nodeId:n.id});});return issues},
  async runWorkflow(id:string):Promise<ExecutionRecord>{const workflow=workflows().find(w=>w.id===id)!;const startedAt=now();const records:NodeExecution[]=workflow.nodes.map((n,i)=>({nodeId:n.id,status:n.id==="notification_failed"?"skipped":"successful",startedAt:new Date(Date.now()+i*120).toISOString(),completedAt:new Date(Date.now()+i*120+60).toISOString(),durationMs:n.type==="http_request"?284:Math.max(2,Math.round(Math.random()*20)),input:i?{dependencies:{[workflow.nodes[i-1].id]:"Structured output"}}:{trigger:{type:"manual"}},output:n.type==="http_request"?{status:200,headers:{"content-type":"text/html"},body:"<!doctype html>…",durationMs:284,finalUrl:"https://example.com/"}:n.type==="condition"?{result:true,left:200,right:200,operator:"equals"}:{delivered:n.type==="desktop_notification"},logs:[n.type==="http_request"?"GET https://example.com/ completed with status 200.":`${n.name} completed.`],retryCount:0,skipReason:n.id==="notification_failed"?"The node was not reached because its branch was not followed.":undefined,branchFollowed:n.type==="condition"?"true":undefined}));const run:ExecutionRecord={id:crypto.randomUUID(),workflowId:id,workflowVersion:1,trigger:{type:"manual"},status:"successful",startedAt,completedAt:now(),durationMs:412,nodeExecutions:records,recoveredAfterCrash:false};saveRuns([run,...runs()]);return run},
  async listExecutions(workflowId?:string){return runs().filter(r=>!workflowId||r.workflowId===workflowId)},async getExecution(id:string){return runs().find(r=>r.id===id)},async clearExecutionHistory(){saveRuns([]);return 0},async cancelExecution(){},
};
