import type { BrowserProfile, BrowserProfileSettings, ConnectionMetadata, ExecutionRecord, NodeExecution, ValidationIssue, Workflow, WorkflowSummary } from "./types";

const KEY="sandbox-preview-workflows"; const RUNS="sandbox-preview-runs";
const PROFILES="sandbox-preview-profiles"; const CONNECTIONS="sandbox-preview-connections";
const now=()=>new Date().toISOString();
const blank=(template="blank"):Workflow=>{
  const id=crypto.randomUUID(); const createdAt=now();
  const base={id,schemaVersion:2,description:"",enabled:false,settings:{defaultNodeTimeoutMs:30000,maxConcurrentNodes:4,permissions:{approvedFolders:[],approvedNetworkDomains:[],approvedBrowserProfileIds:[],browserAutomationPermitted:false,externalCommunicationPermitted:false,commandExecutionPermitted:false,backgroundExecutionPermitted:false}},createdAt,updatedAt:createdAt};
  if(template==="website-change-monitor")return{...base,name:"Website Change Monitor",triggerNodeId:"schedule",settings:{...base.settings,permissions:{...base.settings.permissions,approvedNetworkDomains:["example.com"]}},nodes:[
    {id:"schedule",type:"schedule_trigger",version:1,name:"Every 30 minutes",position:{x:60,y:220},configuration:{scheduleType:"minutes",every:30,time:"09:00",cron:"*/30 * * * *"},disabled:false},
    {id:"browser",type:"open_browser",version:1,name:"Open monitored browser",position:{x:340,y:220},configuration:{profileId:"",headed:false,viewport:{width:1280,height:800},closeAutomatically:true},disabled:false},
    {id:"navigate",type:"navigate",version:1,name:"Open monitored page",position:{x:620,y:220},configuration:{url:"https://example.com",waitCondition:"dom_ready",timeoutMs:30000},disabled:false},
    {id:"extract",type:"extract_data",version:1,name:"Extract page heading",position:{x:900,y:220},configuration:{locator:{primary:{kind:"role",value:"heading",name:"Example Domain"},alternatives:[],tag:"h1",stableAttributes:{},framePath:[],recordingUrl:"https://example.com"},extract:"text",fieldName:"heading",repeated:false},disabled:false},
    {id:"condition",type:"condition",version:1,name:"Has expected heading",position:{x:1180,y:220},configuration:{left:"{{nodes.extract.output.data.heading}}",operator:"contains",right:"Example Domain"},disabled:false},
    {id:"changed",type:"desktop_notification",version:1,name:"Notify when changed",position:{x:1460,y:330},configuration:{title:"Website content changed",message:"The monitored heading changed."},disabled:false}],edges:[
      {id:"e1",sourceNodeId:"schedule",sourceHandle:"output",targetNodeId:"browser",targetHandle:"input"},{id:"e2",sourceNodeId:"browser",sourceHandle:"output",targetNodeId:"navigate",targetHandle:"input"},{id:"e3",sourceNodeId:"navigate",sourceHandle:"output",targetNodeId:"extract",targetHandle:"input"},{id:"e4",sourceNodeId:"extract",sourceHandle:"output",targetNodeId:"condition",targetHandle:"input"},{id:"e5",sourceNodeId:"condition",sourceHandle:"false",targetNodeId:"changed",targetHandle:"input"}]};
  if(template==="download-daily-report")return{...base,name:"Download Daily Report",triggerNodeId:"schedule",nodes:[
    {id:"schedule",type:"schedule_trigger",version:1,name:"Daily at 09:00",position:{x:60,y:220},configuration:{scheduleType:"daily",time:"09:00"},disabled:false},
    {id:"browser",type:"open_browser",version:1,name:"Open reporting profile",position:{x:340,y:220},configuration:{profileId:"",headed:false,viewport:{width:1280,height:800},closeAutomatically:true},disabled:false},
    {id:"navigate",type:"navigate",version:1,name:"Open report portal",position:{x:620,y:220},configuration:{url:"https://example.com",waitCondition:"dom_ready"},disabled:false},
    {id:"download",type:"download_file",version:1,name:"Download report",position:{x:900,y:220},configuration:{locator:{primary:{kind:"role",value:"button",name:"Download report"},alternatives:[],tag:"button",stableAttributes:{},framePath:[],recordingUrl:"https://example.com"},destinationFolder:"",filename:"daily-report.csv"},disabled:false}],edges:[{id:"e1",sourceNodeId:"schedule",sourceHandle:"output",targetNodeId:"browser",targetHandle:"input"},{id:"e2",sourceNodeId:"browser",sourceHandle:"output",targetNodeId:"navigate",targetHandle:"input"},{id:"e3",sourceNodeId:"navigate",sourceHandle:"output",targetNodeId:"download",targetHandle:"input"}]};
  if(template==="email-enquiry-draft")return{...base,name:"Email Enquiry Draft",triggerNodeId:"new_email",nodes:[
    {id:"new_email",type:"gmail_new_email_trigger",version:1,name:"New enquiry email",position:{x:60,y:220},configuration:{credentialId:"",pollIntervalMinutes:5,subjectContains:"enquiry"},disabled:false},
    {id:"condition",type:"condition",version:1,name:"Has a sender",position:{x:340,y:220},configuration:{left:"{{trigger.email.sender}}",operator:"exists",right:null},disabled:false},
    {id:"compose",type:"set_data",version:1,name:"Prepare acknowledgement",position:{x:620,y:150},configuration:{values:{recipient:"{{trigger.email.sender}}",subject:"Re: {{trigger.email.subject}}",body:"Thanks for your enquiry."}},disabled:false},
    {id:"draft",type:"gmail_create_draft",version:1,name:"Create Gmail draft",position:{x:900,y:150},configuration:{credentialId:"",to:"{{nodes.compose.output.recipient}}",subject:"{{nodes.compose.output.subject}}",body:"{{nodes.compose.output.body}}"},disabled:false}],edges:[{id:"e1",sourceNodeId:"new_email",sourceHandle:"output",targetNodeId:"condition",targetHandle:"input"},{id:"e2",sourceNodeId:"condition",sourceHandle:"true",targetNodeId:"compose",targetHandle:"input"},{id:"e3",sourceNodeId:"compose",sourceHandle:"output",targetNodeId:"draft",targetHandle:"input"}]};
  if(template==="website-status-discord")return{...base,name:"Website Status to Discord",triggerNodeId:"schedule",settings:{...base.settings,permissions:{...base.settings.permissions,approvedNetworkDomains:["example.com"]}},nodes:[
    {id:"schedule",type:"schedule_trigger",version:1,name:"Every 15 minutes",position:{x:60,y:220},configuration:{scheduleType:"minutes",every:15},disabled:false},
    {id:"request",type:"http_request",version:1,name:"Check website",position:{x:340,y:220},configuration:{method:"GET",url:"https://example.com",headers:{},query:{}},disabled:false},
    {id:"condition",type:"condition",version:1,name:"Status is healthy",position:{x:620,y:220},configuration:{left:"{{nodes.request.output.status}}",operator:"equals",right:200},disabled:false},
    {id:"discord",type:"discord_webhook",version:1,name:"Alert Discord",position:{x:900,y:330},configuration:{credentialId:"",content:"Website check failed."},disabled:false}],edges:[{id:"e1",sourceNodeId:"schedule",sourceHandle:"output",targetNodeId:"request",targetHandle:"input"},{id:"e2",sourceNodeId:"request",sourceHandle:"output",targetNodeId:"condition",targetHandle:"input"},{id:"e3",sourceNodeId:"condition",sourceHandle:"false",targetNodeId:"discord",targetHandle:"input"}]};
  if(template==="website-health")return{...base,name:"Website Health Monitor",triggerNodeId:"manual_trigger",settings:{...base.settings,permissions:{...base.settings.permissions,approvedNetworkDomains:["example.com"]}},nodes:[
    {id:"manual_trigger",type:"manual_trigger",version:1,name:"Manual Trigger",position:{x:60,y:220},configuration:{},disabled:false},
    {id:"http_request",type:"http_request",version:1,name:"HTTP Request",position:{x:340,y:220},configuration:{method:"GET",url:"https://example.com",timeoutMs:30000,retryCount:1,headers:{},query:{}},disabled:false},
    {id:"condition",type:"condition",version:1,name:"Condition",position:{x:620,y:220},configuration:{left:"{{nodes.http_request.output.status}}",operator:"equals",right:200},disabled:false},
    {id:"notification_success",type:"desktop_notification",version:1,name:"Desktop Notification",position:{x:920,y:150},configuration:{title:"Website is healthy",message:"example.com returned 200"},disabled:false},
    {id:"notification_failed",type:"desktop_notification",version:1,name:"Desktop Notification",position:{x:920,y:330},configuration:{title:"Website needs attention",message:"Check the latest response"},disabled:false}],edges:[
      {id:"e1",sourceNodeId:"manual_trigger",sourceHandle:"output",targetNodeId:"http_request",targetHandle:"input"},{id:"e2",sourceNodeId:"http_request",sourceHandle:"output",targetNodeId:"condition",targetHandle:"input"},{id:"e3",sourceNodeId:"condition",sourceHandle:"true",targetNodeId:"notification_success",targetHandle:"input"},{id:"e4",sourceNodeId:"condition",sourceHandle:"false",targetNodeId:"notification_failed",targetHandle:"input"}]};
  if(template==="downloads-organiser")return{...base,name:"Downloads Folder Organiser",triggerNodeId:"file_watch",nodes:[{id:"file_watch",type:"file_watch_trigger",version:1,name:"File Watch Trigger",position:{x:60,y:220},configuration:{folder:"",events:["created"],pattern:"*.pdf"},disabled:false},{id:"condition",type:"condition",version:1,name:"Condition",position:{x:340,y:220},configuration:{left:"{{trigger.extension}}",operator:"equals",right:"pdf"},disabled:false},{id:"move_file",type:"move_file",version:1,name:"Move File",position:{x:650,y:150},configuration:{source:"{{trigger.path}}",destinationFolder:"",renameTo:"",overwrite:false},disabled:false}],edges:[{id:"e1",sourceNodeId:"file_watch",sourceHandle:"output",targetNodeId:"condition",targetHandle:"input"},{id:"e2",sourceNodeId:"condition",sourceHandle:"true",targetNodeId:"move_file",targetHandle:"input"}]};
  return{...base,name:"Untitled workflow",triggerNodeId:"manual_trigger",nodes:[{id:"manual_trigger",type:"manual_trigger",version:1,name:"Manual Trigger",position:{x:80,y:220},configuration:{},disabled:false}],edges:[]};
};
const workflows=()=>JSON.parse(localStorage.getItem(KEY)??"[]") as Workflow[]; const saveAll=(v:Workflow[])=>localStorage.setItem(KEY,JSON.stringify(v));
const runs=()=>JSON.parse(localStorage.getItem(RUNS)??"[]") as ExecutionRecord[]; const saveRuns=(v:ExecutionRecord[])=>localStorage.setItem(RUNS,JSON.stringify(v));
export const previewApi={
  async listWorkflows():Promise<WorkflowSummary[]>{return workflows().map(workflow=>({workflow,lastExecution:runs().find(r=>r.workflowId===workflow.id)}));},
  async getWorkflow(id:string){return workflows().find(w=>w.id===id)},
  async saveWorkflow(workflow:Workflow){workflow.updatedAt=now();const all=workflows();const i=all.findIndex(w=>w.id===workflow.id);if(i<0)all.unshift(workflow);else all[i]=workflow;saveAll(all);return workflow},
  async createWorkflow(templateKey?:string,name?:string){const w=blank(templateKey);if(name)w.name=name;saveAll([w,...workflows()]);return w},
  async deleteWorkflow(id:string){saveAll(workflows().filter(w=>w.id!==id))},
  async validateWorkflow(workflow:Workflow):Promise<ValidationIssue[]>{const issues:ValidationIssue[]=[];const triggers=workflow.nodes.filter(n=>n.type.endsWith("trigger"));if(triggers.length!==1)issues.push({code:"trigger_count",message:`Workflow requires exactly one trigger; found ${triggers.length}.`});workflow.nodes.forEach(n=>{if(n.type==="http_request"&&!n.configuration.url)issues.push({code:"incomplete_node",message:"HTTP Request requires a URL.",nodeId:n.id});});return issues},
  async runWorkflow(id:string):Promise<ExecutionRecord>{const workflow=workflows().find(w=>w.id===id)!;const startedAt=now();const records:NodeExecution[]=workflow.nodes.map((n,i)=>({nodeId:n.id,status:n.id==="notification_failed"?"skipped":"successful",startedAt:new Date(Date.now()+i*120).toISOString(),completedAt:new Date(Date.now()+i*120+60).toISOString(),durationMs:n.type==="http_request"?284:Math.max(2,Math.round(Math.random()*20)),input:i?{dependencies:{[workflow.nodes[i-1].id]:"Structured output"}}:{trigger:{type:"manual"}},output:n.type==="http_request"?{status:200,headers:{"content-type":"text/html"},body:"<!doctype html>…",durationMs:284,finalUrl:"https://example.com/"}:n.type==="condition"?{result:true,left:200,right:200,operator:"equals"}:{delivered:n.type==="desktop_notification"},logs:[n.type==="http_request"?"GET https://example.com/ completed with status 200.":`${n.name} completed.`],retryCount:0,skipReason:n.id==="notification_failed"?"The node was not reached because its branch was not followed.":undefined,branchFollowed:n.type==="condition"?"true":undefined}));const run:ExecutionRecord={id:crypto.randomUUID(),workflowId:id,workflowVersion:1,trigger:{type:"manual"},status:"successful",startedAt,completedAt:now(),durationMs:412,nodeExecutions:records,recoveredAfterCrash:false};saveRuns([run,...runs()]);return run},
  async retryFailedNode(executionId:string,nodeId:string):Promise<ExecutionRecord>{const previous=runs().find(r=>r.id===executionId);if(!previous)throw new Error("Execution no longer exists.");const failed=previous.nodeExecutions.find(n=>n.nodeId===nodeId&&n.status==="failed");if(!failed)throw new Error("Only a failed node can be retried independently.");const startedAt=now();const nodeExecution:NodeExecution={...failed,status:"successful",startedAt,completedAt:now(),durationMs:12,output:{retried:true},logs:[...failed.logs,"Failed node retry completed."],retryCount:failed.retryCount+1,error:undefined};const run:ExecutionRecord={id:crypto.randomUUID(),workflowId:previous.workflowId,workflowVersion:previous.workflowVersion,trigger:previous.trigger,status:"successful",startedAt,completedAt:now(),durationMs:12,nodeExecutions:[nodeExecution],recoveredAfterCrash:false};saveRuns([run,...runs()]);return run},
  async listExecutions(workflowId?:string){return runs().filter(r=>!workflowId||r.workflowId===workflowId)},async getExecution(id:string){return runs().find(r=>r.id===id)},async clearExecutionHistory(){saveRuns([]);return 0},async cancelExecution(){},
  async listBrowserProfiles(){
    const stored=JSON.parse(localStorage.getItem(PROFILES)??"[]") as Partial<BrowserProfile>[];
    return stored.filter(profile=>profile.id&&profile.name).map(profile=>({...profile,persistent:profile.persistent!==false,dataPath:profile.dataPath??"Managed application data",settings:{viewportWidth:profile.settings?.viewportWidth??1280,viewportHeight:profile.settings?.viewportHeight??800,permissions:profile.settings?.permissions??[],downloadFolder:profile.settings?.downloadFolder,proxy:profile.settings?.proxy,userAgent:profile.settings?.userAgent},createdAt:profile.createdAt??now()} as BrowserProfile));
  },
  async createBrowserProfile(name:string,persistent=true,settings?:BrowserProfileSettings){const profile:BrowserProfile={id:crypto.randomUUID(),name,persistent,dataPath:"Managed application data",settings:settings??{viewportWidth:1280,viewportHeight:800,permissions:[]},createdAt:now()};const profiles=await this.listBrowserProfiles();localStorage.setItem(PROFILES,JSON.stringify([...profiles,profile]));return profile},
  async updateBrowserProfile(id:string,name:string,persistent:boolean,settings:BrowserProfileSettings){const profiles=await this.listBrowserProfiles();const profile=profiles.find(item=>item.id===id)!;Object.assign(profile,{name,persistent,settings});localStorage.setItem(PROFILES,JSON.stringify(profiles));return profile},
  async duplicateBrowserProfile(id:string){const source=(await this.listBrowserProfiles()).find(item=>item.id===id)!;return this.createBrowserProfile(`${source.name} copy`,source.persistent,source.settings)},
  async deleteBrowserProfile(id:string){localStorage.setItem(PROFILES,JSON.stringify((await this.listBrowserProfiles()).filter(item=>item.id!==id)))},
  async listConnections(){return JSON.parse(localStorage.getItem(CONNECTIONS)??"[]") as ConnectionMetadata[]},
};
